// Code generated by protoc-gen-go.
// source: undercroft.proto
// DO NOT EDIT!

/*
Package undercroft is a generated protocol buffer package.

Storage of applications

It is generated from these files:
	undercroft.proto

It has these top-level messages:
	VendorRequest
	VendorRegisterRequest
	VendorRegisterResponse
	VendorResponse
	VendorUpdateRequest
	VendorListRequest
	VendorUpdateResponse
	VendorsResponse
	AppRequest
	AppResponse
	AppsResponse
	AppListRequest
	AppRegisterRequest
	AppRegisterResponse
	AppUpdateRequest
	AppUpdateResponse
*/
package undercroft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VendorRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *VendorRequest) Reset()                    { *m = VendorRequest{} }
func (m *VendorRequest) String() string            { return proto.CompactTextString(m) }
func (*VendorRequest) ProtoMessage()               {}
func (*VendorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VendorRegisterRequest struct {
	OrganisationId string `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
	Id             string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description    string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *VendorRegisterRequest) Reset()                    { *m = VendorRegisterRequest{} }
func (m *VendorRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*VendorRegisterRequest) ProtoMessage()               {}
func (*VendorRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VendorRegisterResponse struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	EntityCode string `protobuf:"bytes,2,opt,name=entity_code,json=entityCode" json:"entity_code,omitempty"`
	Secret     string `protobuf:"bytes,3,opt,name=secret" json:"secret,omitempty"`
}

func (m *VendorRegisterResponse) Reset()                    { *m = VendorRegisterResponse{} }
func (m *VendorRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorRegisterResponse) ProtoMessage()               {}
func (*VendorRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type VendorResponse struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	EntityCode  string `protobuf:"bytes,4,opt,name=entity_code,json=entityCode" json:"entity_code,omitempty"`
}

func (m *VendorResponse) Reset()                    { *m = VendorResponse{} }
func (m *VendorResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorResponse) ProtoMessage()               {}
func (*VendorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type VendorUpdateRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *VendorUpdateRequest) Reset()                    { *m = VendorUpdateRequest{} }
func (m *VendorUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*VendorUpdateRequest) ProtoMessage()               {}
func (*VendorUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type VendorListRequest struct {
	OrganisationId string `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
}

func (m *VendorListRequest) Reset()                    { *m = VendorListRequest{} }
func (m *VendorListRequest) String() string            { return proto.CompactTextString(m) }
func (*VendorListRequest) ProtoMessage()               {}
func (*VendorListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type VendorUpdateResponse struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Updated bool   `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
}

func (m *VendorUpdateResponse) Reset()                    { *m = VendorUpdateResponse{} }
func (m *VendorUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorUpdateResponse) ProtoMessage()               {}
func (*VendorUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type VendorsResponse struct {
	Vendors []*VendorResponse `protobuf:"bytes,1,rep,name=vendors" json:"vendors,omitempty"`
}

func (m *VendorsResponse) Reset()                    { *m = VendorsResponse{} }
func (m *VendorsResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorsResponse) ProtoMessage()               {}
func (*VendorsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *VendorsResponse) GetVendors() []*VendorResponse {
	if m != nil {
		return m.Vendors
	}
	return nil
}

type AppRequest struct {
	VendorId    string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	IncludeYaml bool   `protobuf:"varint,3,opt,name=include_yaml,json=includeYaml" json:"include_yaml,omitempty"`
}

func (m *AppRequest) Reset()                    { *m = AppRequest{} }
func (m *AppRequest) String() string            { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()               {}
func (*AppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type AppResponse struct {
	VendorId       string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	Id             string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	DefinitionYaml string `protobuf:"bytes,3,opt,name=definition_yaml,json=definitionYaml" json:"definition_yaml,omitempty"`
}

func (m *AppResponse) Reset()                    { *m = AppResponse{} }
func (m *AppResponse) String() string            { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()               {}
func (*AppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type AppsResponse struct {
	Apps []*AppResponse `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
}

func (m *AppsResponse) Reset()                    { *m = AppsResponse{} }
func (m *AppsResponse) String() string            { return proto.CompactTextString(m) }
func (*AppsResponse) ProtoMessage()               {}
func (*AppsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AppsResponse) GetApps() []*AppResponse {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppListRequest struct {
	VendorId    string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	IncludeYaml bool   `protobuf:"varint,2,opt,name=include_yaml,json=includeYaml" json:"include_yaml,omitempty"`
}

func (m *AppListRequest) Reset()                    { *m = AppListRequest{} }
func (m *AppListRequest) String() string            { return proto.CompactTextString(m) }
func (*AppListRequest) ProtoMessage()               {}
func (*AppListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type AppRegisterRequest struct {
	VendorId       string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	Id             string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	VendorSecret   string `protobuf:"bytes,3,opt,name=vendor_secret,json=vendorSecret" json:"vendor_secret,omitempty"`
	DefinitionYaml string `protobuf:"bytes,4,opt,name=definition_yaml,json=definitionYaml" json:"definition_yaml,omitempty"`
}

func (m *AppRegisterRequest) Reset()                    { *m = AppRegisterRequest{} }
func (m *AppRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*AppRegisterRequest) ProtoMessage()               {}
func (*AppRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type AppRegisterResponse struct {
	VendorId   string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	EntityCode string `protobuf:"bytes,3,opt,name=entity_code,json=entityCode" json:"entity_code,omitempty"`
}

func (m *AppRegisterResponse) Reset()                    { *m = AppRegisterResponse{} }
func (m *AppRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*AppRegisterResponse) ProtoMessage()               {}
func (*AppRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type AppUpdateRequest struct {
	VendorId       string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	Id             string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	DefinitionYaml string `protobuf:"bytes,3,opt,name=definition_yaml,json=definitionYaml" json:"definition_yaml,omitempty"`
}

func (m *AppUpdateRequest) Reset()                    { *m = AppUpdateRequest{} }
func (m *AppUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*AppUpdateRequest) ProtoMessage()               {}
func (*AppUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type AppUpdateResponse struct {
	VendorId string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Updated  bool   `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
}

func (m *AppUpdateResponse) Reset()                    { *m = AppUpdateResponse{} }
func (m *AppUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*AppUpdateResponse) ProtoMessage()               {}
func (*AppUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func init() {
	proto.RegisterType((*VendorRequest)(nil), "undercroft.VendorRequest")
	proto.RegisterType((*VendorRegisterRequest)(nil), "undercroft.VendorRegisterRequest")
	proto.RegisterType((*VendorRegisterResponse)(nil), "undercroft.VendorRegisterResponse")
	proto.RegisterType((*VendorResponse)(nil), "undercroft.VendorResponse")
	proto.RegisterType((*VendorUpdateRequest)(nil), "undercroft.VendorUpdateRequest")
	proto.RegisterType((*VendorListRequest)(nil), "undercroft.VendorListRequest")
	proto.RegisterType((*VendorUpdateResponse)(nil), "undercroft.VendorUpdateResponse")
	proto.RegisterType((*VendorsResponse)(nil), "undercroft.VendorsResponse")
	proto.RegisterType((*AppRequest)(nil), "undercroft.AppRequest")
	proto.RegisterType((*AppResponse)(nil), "undercroft.AppResponse")
	proto.RegisterType((*AppsResponse)(nil), "undercroft.AppsResponse")
	proto.RegisterType((*AppListRequest)(nil), "undercroft.AppListRequest")
	proto.RegisterType((*AppRegisterRequest)(nil), "undercroft.AppRegisterRequest")
	proto.RegisterType((*AppRegisterResponse)(nil), "undercroft.AppRegisterResponse")
	proto.RegisterType((*AppUpdateRequest)(nil), "undercroft.AppUpdateRequest")
	proto.RegisterType((*AppUpdateResponse)(nil), "undercroft.AppUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Undercroft service

type UndercroftClient interface {
	RetrieveVendor(ctx context.Context, in *VendorRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	UpdateVendor(ctx context.Context, in *VendorUpdateRequest, opts ...grpc.CallOption) (*VendorUpdateResponse, error)
	RegisterVendor(ctx context.Context, in *VendorRegisterRequest, opts ...grpc.CallOption) (*VendorRegisterResponse, error)
	ListVendors(ctx context.Context, in *VendorListRequest, opts ...grpc.CallOption) (*VendorsResponse, error)
	RetrieveApp(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppResponse, error)
	ListApps(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*AppsResponse, error)
	RegisterApp(ctx context.Context, in *AppRegisterRequest, opts ...grpc.CallOption) (*AppRegisterResponse, error)
	UpdateApp(ctx context.Context, in *AppUpdateRequest, opts ...grpc.CallOption) (*AppUpdateResponse, error)
}

type undercroftClient struct {
	cc *grpc.ClientConn
}

func NewUndercroftClient(cc *grpc.ClientConn) UndercroftClient {
	return &undercroftClient{cc}
}

func (c *undercroftClient) RetrieveVendor(ctx context.Context, in *VendorRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	out := new(VendorResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/RetrieveVendor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) UpdateVendor(ctx context.Context, in *VendorUpdateRequest, opts ...grpc.CallOption) (*VendorUpdateResponse, error) {
	out := new(VendorUpdateResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/UpdateVendor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) RegisterVendor(ctx context.Context, in *VendorRegisterRequest, opts ...grpc.CallOption) (*VendorRegisterResponse, error) {
	out := new(VendorRegisterResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/RegisterVendor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) ListVendors(ctx context.Context, in *VendorListRequest, opts ...grpc.CallOption) (*VendorsResponse, error) {
	out := new(VendorsResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/ListVendors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) RetrieveApp(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppResponse, error) {
	out := new(AppResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/RetrieveApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) ListApps(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*AppsResponse, error) {
	out := new(AppsResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/ListApps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) RegisterApp(ctx context.Context, in *AppRegisterRequest, opts ...grpc.CallOption) (*AppRegisterResponse, error) {
	out := new(AppRegisterResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/RegisterApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *undercroftClient) UpdateApp(ctx context.Context, in *AppUpdateRequest, opts ...grpc.CallOption) (*AppUpdateResponse, error) {
	out := new(AppUpdateResponse)
	err := grpc.Invoke(ctx, "/undercroft.Undercroft/UpdateApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Undercroft service

type UndercroftServer interface {
	RetrieveVendor(context.Context, *VendorRequest) (*VendorResponse, error)
	UpdateVendor(context.Context, *VendorUpdateRequest) (*VendorUpdateResponse, error)
	RegisterVendor(context.Context, *VendorRegisterRequest) (*VendorRegisterResponse, error)
	ListVendors(context.Context, *VendorListRequest) (*VendorsResponse, error)
	RetrieveApp(context.Context, *AppRequest) (*AppResponse, error)
	ListApps(context.Context, *AppListRequest) (*AppsResponse, error)
	RegisterApp(context.Context, *AppRegisterRequest) (*AppRegisterResponse, error)
	UpdateApp(context.Context, *AppUpdateRequest) (*AppUpdateResponse, error)
}

func RegisterUndercroftServer(s *grpc.Server, srv UndercroftServer) {
	s.RegisterService(&_Undercroft_serviceDesc, srv)
}

func _Undercroft_RetrieveVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).RetrieveVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/RetrieveVendor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).RetrieveVendor(ctx, req.(*VendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_UpdateVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).UpdateVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/UpdateVendor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).UpdateVendor(ctx, req.(*VendorUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_RegisterVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).RegisterVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/RegisterVendor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).RegisterVendor(ctx, req.(*VendorRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_ListVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).ListVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/ListVendors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).ListVendors(ctx, req.(*VendorListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_RetrieveApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).RetrieveApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/RetrieveApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).RetrieveApp(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/ListApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).ListApps(ctx, req.(*AppListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_RegisterApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).RegisterApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/RegisterApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).RegisterApp(ctx, req.(*AppRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Undercroft_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UndercroftServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/undercroft.Undercroft/UpdateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UndercroftServer).UpdateApp(ctx, req.(*AppUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Undercroft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "undercroft.Undercroft",
	HandlerType: (*UndercroftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveVendor",
			Handler:    _Undercroft_RetrieveVendor_Handler,
		},
		{
			MethodName: "UpdateVendor",
			Handler:    _Undercroft_UpdateVendor_Handler,
		},
		{
			MethodName: "RegisterVendor",
			Handler:    _Undercroft_RegisterVendor_Handler,
		},
		{
			MethodName: "ListVendors",
			Handler:    _Undercroft_ListVendors_Handler,
		},
		{
			MethodName: "RetrieveApp",
			Handler:    _Undercroft_RetrieveApp_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _Undercroft_ListApps_Handler,
		},
		{
			MethodName: "RegisterApp",
			Handler:    _Undercroft_RegisterApp_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _Undercroft_UpdateApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("undercroft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xdb, 0x68, 0x6b, 0x6f, 0xba, 0x6e, 0xf3, 0xa0, 0x94, 0x8c, 0xd1, 0xce, 0x3c, 0x30,
	0x09, 0x69, 0x0f, 0x83, 0x37, 0x10, 0x1a, 0xe2, 0x61, 0x4c, 0x42, 0x08, 0x82, 0x06, 0xe2, 0x43,
	0xaa, 0x42, 0xe2, 0x0d, 0x4b, 0x5b, 0x12, 0x12, 0x77, 0x68, 0x7f, 0x80, 0x57, 0xfe, 0x26, 0x3f,
	0x03, 0xc7, 0x76, 0x1a, 0x3b, 0x1f, 0x95, 0x5a, 0x69, 0x6f, 0xcd, 0xf1, 0xf5, 0xb9, 0xe7, 0x9e,
	0xeb, 0x33, 0x0d, 0xb6, 0x66, 0x61, 0x40, 0x12, 0x3f, 0x89, 0xce, 0xd9, 0x61, 0x9c, 0x44, 0x2c,
	0x42, 0x50, 0x20, 0x78, 0x0c, 0x1b, 0x9f, 0x48, 0x18, 0x44, 0x89, 0x4b, 0x7e, 0xcd, 0x48, 0xca,
	0xd0, 0x00, 0xda, 0x34, 0x18, 0xb5, 0x26, 0xad, 0x83, 0x9e, 0xcb, 0x7f, 0xe1, 0x3f, 0x2d, 0xb8,
	0x9b, 0x57, 0x5c, 0xd0, 0x94, 0x91, 0x79, 0xe5, 0x63, 0xd8, 0x8c, 0x92, 0x0b, 0x2f, 0xa4, 0xa9,
	0xc7, 0x68, 0x14, 0x4e, 0xe7, 0xd7, 0x06, 0x3a, 0x7c, 0x1a, 0x28, 0xca, 0x76, 0x4e, 0x89, 0x10,
	0x58, 0xa1, 0x77, 0x45, 0x46, 0x1d, 0x81, 0x88, 0xdf, 0x68, 0x02, 0x76, 0x40, 0x52, 0x3f, 0xa1,
	0x71, 0x76, 0x69, 0x64, 0x89, 0x23, 0x1d, 0xc2, 0x1e, 0x0c, 0xcb, 0x3a, 0xd2, 0x38, 0x0a, 0x53,
	0x52, 0x96, 0x8c, 0xc6, 0x60, 0x93, 0x90, 0x51, 0x76, 0x33, 0xf5, 0xa3, 0x80, 0xa8, 0xc6, 0x20,
	0xa1, 0xd7, 0x1c, 0x41, 0x43, 0x58, 0x4b, 0x89, 0x9f, 0x10, 0xa6, 0x24, 0xa8, 0x2f, 0xfc, 0x1b,
	0x06, 0x79, 0x8b, 0x06, 0xea, 0x5c, 0x7a, 0xbb, 0x59, 0x7a, 0xa7, 0x22, 0xbd, 0x2c, 0xc8, 0x2a,
	0x0b, 0xc2, 0xdf, 0x60, 0x47, 0x36, 0x3e, 0x8b, 0x03, 0x8f, 0x91, 0x86, 0x5d, 0xac, 0xd6, 0x1d,
	0xbf, 0x80, 0x6d, 0x49, 0xfe, 0x96, 0xdb, 0xb6, 0xec, 0xf2, 0xf0, 0x31, 0xdc, 0x31, 0xa5, 0x35,
	0x38, 0x33, 0x82, 0xf5, 0x99, 0xa8, 0x90, 0x9b, 0xee, 0xba, 0xf9, 0x27, 0x3e, 0x81, 0x4d, 0xc9,
	0x90, 0xce, 0x2f, 0x3f, 0x83, 0xf5, 0x6b, 0x09, 0x71, 0x86, 0xce, 0x81, 0x7d, 0xe4, 0x1c, 0x6a,
	0xaf, 0xd4, 0xdc, 0x81, 0x9b, 0x97, 0xe2, 0xef, 0x00, 0xaf, 0xe2, 0x38, 0x9f, 0x60, 0x17, 0x7a,
	0xf2, 0xa0, 0xd0, 0xde, 0x95, 0x40, 0xcd, 0x93, 0xdb, 0x87, 0x3e, 0x0d, 0xfd, 0xcb, 0x59, 0x40,
	0xa6, 0x37, 0xde, 0xd5, 0xa5, 0xb0, 0xa9, 0xeb, 0xda, 0x0a, 0xfb, 0xc2, 0x21, 0xec, 0x83, 0x2d,
	0xd8, 0x95, 0xc4, 0xa5, 0xe8, 0xb9, 0x9b, 0x01, 0x39, 0xa7, 0x21, 0x15, 0x5e, 0xce, 0x3b, 0x70,
	0x37, 0x0b, 0x58, 0x34, 0x79, 0x0e, 0x7d, 0xde, 0xa4, 0x30, 0xe2, 0x09, 0x58, 0x1e, 0xff, 0x56,
	0x2e, 0xdc, 0xd3, 0x5d, 0xd0, 0xc4, 0xb8, 0xa2, 0x08, 0xbf, 0x87, 0x01, 0x07, 0xf5, 0x2d, 0x2e,
	0x14, 0x59, 0x9e, 0xb9, 0x5d, 0x9d, 0xf9, 0x6f, 0x0b, 0x90, 0xe8, 0x63, 0x26, 0x7b, 0xa9, 0xd9,
	0x1f, 0xc1, 0x86, 0x2a, 0x36, 0x32, 0xd5, 0x97, 0xe0, 0x47, 0x81, 0xd5, 0x19, 0x64, 0xd5, 0x1a,
	0xe4, 0xc3, 0x8e, 0x21, 0x68, 0x95, 0x6d, 0x94, 0xe2, 0xd6, 0xa9, 0xc4, 0xed, 0x27, 0x6c, 0xf1,
	0x26, 0x66, 0xd6, 0x6e, 0x67, 0xdf, 0x5f, 0x61, 0x5b, 0xeb, 0xb4, 0xca, 0x30, 0x5a, 0xae, 0x3a,
	0x46, 0xae, 0x8e, 0xfe, 0x59, 0x00, 0x67, 0xf3, 0xf7, 0x82, 0x4e, 0x60, 0xe0, 0x12, 0x96, 0x50,
	0x72, 0x4d, 0x64, 0x80, 0xd0, 0xfd, 0xba, 0x50, 0x89, 0x69, 0x9d, 0x05, 0x79, 0x43, 0x1f, 0xa0,
	0x2f, 0x05, 0x2b, 0x9a, 0x71, 0xb5, 0xd6, 0xb0, 0xce, 0x99, 0x34, 0x17, 0x28, 0xca, 0xcf, 0x99,
	0x36, 0xb9, 0x52, 0x45, 0xba, 0x5f, 0x27, 0xc0, 0x78, 0x85, 0x0e, 0x5e, 0x54, 0xa2, 0x88, 0x4f,
	0xc1, 0xce, 0xf2, 0xa0, 0xfe, 0xbe, 0xa0, 0xbd, 0xea, 0x15, 0x2d, 0x2e, 0xce, 0x6e, 0xf5, 0xb8,
	0x88, 0xe2, 0x4b, 0xb0, 0x73, 0xff, 0xf8, 0xca, 0xd0, 0xb0, 0x92, 0x45, 0xc9, 0xd1, 0x94, 0x51,
	0x74, 0x0c, 0xdd, 0xac, 0x57, 0x16, 0x6f, 0xe4, 0x94, 0x8a, 0x74, 0x11, 0xa3, 0xd2, 0x59, 0xa1,
	0xe0, 0x5d, 0xa6, 0x40, 0x0e, 0x98, 0x29, 0x78, 0x58, 0xe9, 0x64, 0xfa, 0x33, 0x6e, 0x3c, 0x57,
	0x7c, 0x6f, 0xa0, 0x27, 0xf7, 0x90, 0xb1, 0x3d, 0x28, 0x55, 0x9b, 0x2b, 0xdc, 0x6b, 0x38, 0x95,
	0x4c, 0x3f, 0xd6, 0xc4, 0x3f, 0x0e, 0x4f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xbf, 0x36,
	0x9e, 0x4c, 0x08, 0x00, 0x00,
}
