// Code generated by protoc-gen-go.
// source: metaroute.proto
// DO NOT EDIT!

/*
Package metaroute is a generated protocol buffer package.

It is generated from these files:
	metaroute.proto

It has these top-level messages:
	HTTPRequest
	HTTPResponse
*/
package metaroute

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HTTPRequest struct {
	Host        string                                `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Path        string                                `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Method      string                                `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	PostParams  map[string]*HTTPRequest_HTTPParameter `protobuf:"bytes,4,rep,name=post_params,json=postParams" json:"post_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryString string                                `protobuf:"bytes,5,opt,name=query_string,json=queryString" json:"query_string,omitempty"`
	Headers     map[string]*HTTPRequest_HTTPParameter `protobuf:"bytes,6,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body        string                                `protobuf:"bytes,7,opt,name=body" json:"body,omitempty"`
	Language    string                                `protobuf:"bytes,8,opt,name=language" json:"language,omitempty"`
	ContentType string                                `protobuf:"bytes,9,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Customer    *HTTPRequest_CustomerInformation      `protobuf:"bytes,10,opt,name=customer" json:"customer,omitempty"`
}

func (m *HTTPRequest) Reset()                    { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()               {}
func (*HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HTTPRequest) GetPostParams() map[string]*HTTPRequest_HTTPParameter {
	if m != nil {
		return m.PostParams
	}
	return nil
}

func (m *HTTPRequest) GetHeaders() map[string]*HTTPRequest_HTTPParameter {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPRequest) GetCustomer() *HTTPRequest_CustomerInformation {
	if m != nil {
		return m.Customer
	}
	return nil
}

type HTTPRequest_HTTPParameter struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *HTTPRequest_HTTPParameter) Reset()                    { *m = HTTPRequest_HTTPParameter{} }
func (m *HTTPRequest_HTTPParameter) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest_HTTPParameter) ProtoMessage()               {}
func (*HTTPRequest_HTTPParameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type HTTPRequest_CustomerInformation struct {
	BrandId      string            `protobuf:"bytes,1,opt,name=brand_id,json=brandId" json:"brand_id,omitempty"`
	CustomerFid  string            `protobuf:"bytes,2,opt,name=customer_fid,json=customerFid" json:"customer_fid,omitempty"`
	CustomerName string            `protobuf:"bytes,3,opt,name=customer_name,json=customerName" json:"customer_name,omitempty"`
	Meta         map[string]string `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HTTPRequest_CustomerInformation) Reset()         { *m = HTTPRequest_CustomerInformation{} }
func (m *HTTPRequest_CustomerInformation) String() string { return proto.CompactTextString(m) }
func (*HTTPRequest_CustomerInformation) ProtoMessage()    {}
func (*HTTPRequest_CustomerInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 3}
}

func (m *HTTPRequest_CustomerInformation) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type HTTPResponse struct {
	StatusCode  int32                                        `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Body        string                                       `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	ContentType string                                       `protobuf:"bytes,3,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Language    string                                       `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Headers     map[string]*HTTPResponse_HTTPHeaderParameter `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HTTPResponse) Reset()                    { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string            { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()               {}
func (*HTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HTTPResponse) GetHeaders() map[string]*HTTPResponse_HTTPHeaderParameter {
	if m != nil {
		return m.Headers
	}
	return nil
}

type HTTPResponse_HTTPHeaderParameter struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *HTTPResponse_HTTPHeaderParameter) Reset()         { *m = HTTPResponse_HTTPHeaderParameter{} }
func (m *HTTPResponse_HTTPHeaderParameter) String() string { return proto.CompactTextString(m) }
func (*HTTPResponse_HTTPHeaderParameter) ProtoMessage()    {}
func (*HTTPResponse_HTTPHeaderParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func init() {
	proto.RegisterType((*HTTPRequest)(nil), "metaroute.HTTPRequest")
	proto.RegisterType((*HTTPRequest_HTTPParameter)(nil), "metaroute.HTTPRequest.HTTPParameter")
	proto.RegisterType((*HTTPRequest_CustomerInformation)(nil), "metaroute.HTTPRequest.CustomerInformation")
	proto.RegisterType((*HTTPResponse)(nil), "metaroute.HTTPResponse")
	proto.RegisterType((*HTTPResponse_HTTPHeaderParameter)(nil), "metaroute.HTTPResponse.HTTPHeaderParameter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MetaRoute service

type MetaRouteClient interface {
	HandleHTTPRequest(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type metaRouteClient struct {
	cc *grpc.ClientConn
}

func NewMetaRouteClient(cc *grpc.ClientConn) MetaRouteClient {
	return &metaRouteClient{cc}
}

func (c *metaRouteClient) HandleHTTPRequest(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	out := new(HTTPResponse)
	err := grpc.Invoke(ctx, "/metaroute.MetaRoute/HandleHTTPRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MetaRoute service

type MetaRouteServer interface {
	HandleHTTPRequest(context.Context, *HTTPRequest) (*HTTPResponse, error)
}

func RegisterMetaRouteServer(s *grpc.Server, srv MetaRouteServer) {
	s.RegisterService(&_MetaRoute_serviceDesc, srv)
}

func _MetaRoute_HandleHTTPRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaRouteServer).HandleHTTPRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metaroute.MetaRoute/HandleHTTPRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaRouteServer).HandleHTTPRequest(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaRoute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metaroute.MetaRoute",
	HandlerType: (*MetaRouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHTTPRequest",
			Handler:    _MetaRoute_HandleHTTPRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("metaroute.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xbf, 0xd6, 0xf6, 0x66, 0xd3, 0xc0, 0x43, 0x23, 0xe4, 0x85, 0xb1, 0x01, 0x9b, 0x40,
	0x6b, 0xa5, 0x82, 0x04, 0x9a, 0x04, 0x12, 0x0c, 0x46, 0xf7, 0x00, 0x2a, 0xa1, 0x4f, 0xbc, 0x04,
	0xb7, 0x71, 0xd3, 0x88, 0xd6, 0x0e, 0xb6, 0x83, 0xd4, 0x47, 0xfe, 0x26, 0x7f, 0x85, 0x17, 0xfc,
	0x45, 0x16, 0xfa, 0xa1, 0xf1, 0xc2, 0x9b, 0x7d, 0x7c, 0xae, 0xcf, 0xf5, 0xb9, 0x27, 0x81, 0xdd,
	0x39, 0x91, 0x98, 0xb3, 0x5c, 0x92, 0x4e, 0xc6, 0x99, 0x64, 0xa8, 0x5d, 0x00, 0x87, 0x3f, 0x9a,
	0xe0, 0xf5, 0x87, 0xc3, 0x41, 0x48, 0xbe, 0xe5, 0x44, 0x48, 0x84, 0xa0, 0x3e, 0x65, 0x42, 0xfa,
	0x95, 0x83, 0xca, 0x49, 0x3b, 0x34, 0x6b, 0x8d, 0x65, 0x58, 0x4e, 0xfd, 0xaa, 0xc5, 0xf4, 0x1a,
	0xed, 0xc3, 0x96, 0xba, 0x64, 0xca, 0x62, 0xbf, 0x66, 0x50, 0xb7, 0x43, 0xef, 0xc0, 0xcb, 0x54,
	0x4d, 0x94, 0x61, 0x8e, 0xe7, 0xc2, 0xaf, 0x1f, 0xd4, 0x4e, 0xbc, 0xde, 0xc3, 0xce, 0x55, 0x07,
	0x25, 0xb1, 0xce, 0x40, 0x31, 0x07, 0x86, 0xf8, 0x96, 0x4a, 0xbe, 0x08, 0x21, 0x2b, 0x00, 0x74,
	0x0f, 0xb6, 0x15, 0x89, 0x2f, 0x22, 0x21, 0x79, 0x4a, 0x13, 0xbf, 0x61, 0x64, 0x3c, 0x83, 0x7d,
	0x32, 0x10, 0x7a, 0x01, 0xcd, 0x29, 0xc1, 0x31, 0xe1, 0xc2, 0xdf, 0x32, 0x3a, 0x47, 0x1b, 0x74,
	0xfa, 0x96, 0x65, 0x45, 0xfe, 0xd4, 0xe8, 0x67, 0x8d, 0x58, 0xbc, 0xf0, 0x9b, 0xf6, 0x59, 0x7a,
	0x8d, 0x02, 0x68, 0xcd, 0x30, 0x4d, 0x72, 0x9c, 0x10, 0xbf, 0x65, 0xf0, 0x62, 0xaf, 0x3b, 0x1a,
	0x33, 0x2a, 0x09, 0x95, 0x91, 0x5c, 0x64, 0xc4, 0x6f, 0xdb, 0x8e, 0x1c, 0x36, 0x54, 0x10, 0xba,
	0x80, 0xd6, 0x38, 0x17, 0x92, 0xcd, 0x09, 0xf7, 0x41, 0x1d, 0x7b, 0xbd, 0x47, 0x1b, 0x5a, 0x3a,
	0x77, 0xb4, 0x4b, 0x3a, 0x61, 0x7c, 0x8e, 0x65, 0xca, 0x68, 0x58, 0xd4, 0x06, 0xc7, 0xb0, 0xa3,
	0xc9, 0xc6, 0x0a, 0x22, 0x09, 0xd7, 0x76, 0x7f, 0xc7, 0x33, 0x55, 0xa9, 0x06, 0x53, 0xd3, 0x76,
	0xdb, 0x5d, 0x30, 0x86, 0xdd, 0x25, 0x13, 0xd1, 0x0d, 0xa8, 0x7d, 0x25, 0x0b, 0x37, 0x40, 0xbd,
	0x44, 0x67, 0xd0, 0x30, 0x74, 0x33, 0x40, 0xaf, 0x77, 0x7f, 0x93, 0x4b, 0x65, 0xc5, 0xd0, 0x96,
	0x9c, 0x55, 0x9f, 0x57, 0x82, 0x2f, 0xb0, 0x5d, 0x76, 0xf0, 0x3f, 0x28, 0xfc, 0xaa, 0xc0, 0xde,
	0x1a, 0x47, 0xd0, 0x1d, 0x68, 0x8d, 0x38, 0xa6, 0x71, 0x94, 0xc6, 0x4e, 0xae, 0x69, 0xf6, 0x97,
	0xb1, 0x99, 0x86, 0xab, 0x88, 0x26, 0xea, 0xb8, 0xea, 0xa6, 0xe1, 0xb0, 0x8b, 0x34, 0x46, 0x47,
	0xb0, 0x53, 0x50, 0xa8, 0x12, 0x75, 0x51, 0x2d, 0xea, 0x3e, 0x28, 0x0c, 0xf5, 0xa1, 0xae, 0x9b,
	0x75, 0x49, 0x7d, 0xfa, 0xef, 0xe3, 0xea, 0xbc, 0x57, 0x4c, 0x1b, 0x29, 0x73, 0x43, 0xf0, 0x0c,
	0xda, 0x05, 0xb4, 0xc6, 0xa3, 0x5b, 0x65, 0x8f, 0xda, 0xa5, 0xd7, 0x1f, 0xfe, 0xac, 0x2a, 0x83,
	0x8d, 0x98, 0xc8, 0x18, 0x15, 0x04, 0xdd, 0x05, 0x4f, 0x48, 0x2c, 0x73, 0x11, 0x8d, 0x59, 0x4c,
	0xcc, 0x25, 0x8d, 0x10, 0x2c, 0x74, 0xae, 0x90, 0x22, 0xba, 0xd5, 0x52, 0x74, 0x97, 0xe3, 0x59,
	0x5b, 0x8d, 0x67, 0x39, 0xdd, 0xf5, 0xa5, 0x74, 0xbf, 0xbc, 0xfa, 0x98, 0x1a, 0xc6, 0x8a, 0xd5,
	0x21, 0xda, 0xee, 0xd6, 0x7f, 0x4d, 0xc1, 0x29, 0xec, 0x69, 0x96, 0x3d, 0xbc, 0x3e, 0xb8, 0xc9,
	0xb5, 0x99, 0x7a, 0xf5, 0x77, 0xa6, 0x1e, 0x6f, 0x6c, 0x67, 0x55, 0xb5, 0x64, 0x6e, 0xef, 0xa3,
	0x9d, 0x4a, 0xa8, 0x0b, 0xd1, 0x1b, 0xb8, 0xd9, 0x57, 0xf1, 0x99, 0x91, 0xf2, 0x2f, 0x6f, 0x7f,
	0xfd, 0xcc, 0x83, 0xdb, 0x1b, 0x14, 0x5f, 0x1f, 0x7f, 0x7e, 0x90, 0xa4, 0x72, 0x9a, 0x8f, 0x3a,
	0x63, 0x36, 0xef, 0xaa, 0x40, 0xc8, 0x74, 0x92, 0x76, 0xcd, 0xaf, 0xf5, 0x34, 0x61, 0xdd, 0xa2,
	0x6a, 0xb4, 0x65, 0xb0, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x83, 0xc3, 0xf1, 0x4c, 0x81,
	0x05, 0x00, 0x00,
}
