// Code generated by protoc-gen-go.
// source: customer.proto
// DO NOT EDIT!

/*
Package customers is a generated protocol buffer package.

It is generated from these files:
	customer.proto

It has these top-level messages:
*/
package customers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import fcommon "github.com/fortifi/proto-go/fcommon"
import fortifi_customer "github.com/fortifi/proto-go/ftypes/customer"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Customer service

type CustomerClient interface {
	Retrieve(ctx context.Context, in *fcommon.IDRequest, opts ...grpc.CallOption) (*fortifi_customer.Customer, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) Retrieve(ctx context.Context, in *fcommon.IDRequest, opts ...grpc.CallOption) (*fortifi_customer.Customer, error) {
	out := new(fortifi_customer.Customer)
	err := grpc.Invoke(ctx, "/customers.Customer/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Customer service

type CustomerServer interface {
	Retrieve(context.Context, *fcommon.IDRequest) (*fortifi_customer.Customer, error)
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(fcommon.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customers.Customer/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Retrieve(ctx, req.(*fcommon.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customers.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _Customer_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2e, 0x2d, 0x2e,
	0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xf1, 0x8b, 0xa5,
	0x78, 0xd3, 0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x20, 0x32, 0x52, 0xa2, 0x69, 0x25, 0x95, 0x05,
	0xa9, 0xc5, 0xfa, 0xa8, 0x1a, 0x8c, 0xdc, 0xb8, 0x38, 0x9c, 0xa1, 0x22, 0x42, 0x56, 0x5c, 0x1c,
	0x41, 0xa9, 0x25, 0x45, 0x99, 0xa9, 0x65, 0xa9, 0x42, 0x42, 0x7a, 0x30, 0xed, 0x9e, 0x2e, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x52, 0x52, 0x7a, 0x69, 0xf9, 0x45, 0x25, 0x99, 0x69, 0x99,
	0x7a, 0x70, 0x43, 0x60, 0x7a, 0x9d, 0xd4, 0xa3, 0x54, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4,
	0x92, 0xf3, 0x73, 0xf5, 0xa1, 0xea, 0xf4, 0xc1, 0x76, 0xe8, 0xa6, 0xe7, 0xc3, 0x6d, 0x2d, 0x4e,
	0x62, 0x03, 0x8b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x0a, 0x14, 0x0f, 0xba, 0x00,
	0x00, 0x00,
}
