// Code generated by protoc-gen-go.
// source: organisations.proto
// DO NOT EDIT!

/*
Package organisations is a generated protocol buffer package.

It is generated from these files:
	organisations.proto

It has these top-level messages:
	CreateRequest
	RetrieveRequest
	OrganisationResponse
	AddMemberRequest
	RemoveMemberRequest
	InviteRequest
	InviteStatusResponse
	ActionInviteRequest
	MemberStatusResponse
	GetMembersRequest
	GetOrganisationsRequest
	MembersResponse
	OrganisationsResponse
*/
package organisations

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_SANDBOX    Mode = 0
	Mode_PRODUCTION Mode = 1
)

var Mode_name = map[int32]string{
	0: "SANDBOX",
	1: "PRODUCTION",
}
var Mode_value = map[string]int32{
	"SANDBOX":    0,
	"PRODUCTION": 1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Region int32

const (
	Region_GLOBAL Region = 0
	Region_US     Region = 1
	Region_EUROPE Region = 2
	Region_ASIA   Region = 3
)

var Region_name = map[int32]string{
	0: "GLOBAL",
	1: "US",
	2: "EUROPE",
	3: "ASIA",
}
var Region_value = map[string]int32{
	"GLOBAL": 0,
	"US":     1,
	"EUROPE": 2,
	"ASIA":   3,
}

func (x Region) String() string {
	return proto.EnumName(Region_name, int32(x))
}
func (Region) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MemberType int32

const (
	MemberType_OWNER   MemberType = 0
	MemberType_MEMBER  MemberType = 1
	MemberType_VIEWER  MemberType = 2
	MemberType_SUPPORT MemberType = 3
)

var MemberType_name = map[int32]string{
	0: "OWNER",
	1: "MEMBER",
	2: "VIEWER",
	3: "SUPPORT",
}
var MemberType_value = map[string]int32{
	"OWNER":   0,
	"MEMBER":  1,
	"VIEWER":  2,
	"SUPPORT": 3,
}

func (x MemberType) String() string {
	return proto.EnumName(MemberType_name, int32(x))
}
func (MemberType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InviteStatus int32

const (
	InviteStatus_PENDING   InviteStatus = 0
	InviteStatus_ACCEPTED  InviteStatus = 1
	InviteStatus_REJECTED  InviteStatus = 2
	InviteStatus_EXPIRED   InviteStatus = 3
	InviteStatus_NOT_FOUND InviteStatus = 4
)

var InviteStatus_name = map[int32]string{
	0: "PENDING",
	1: "ACCEPTED",
	2: "REJECTED",
	3: "EXPIRED",
	4: "NOT_FOUND",
}
var InviteStatus_value = map[string]int32{
	"PENDING":   0,
	"ACCEPTED":  1,
	"REJECTED":  2,
	"EXPIRED":   3,
	"NOT_FOUND": 4,
}

func (x InviteStatus) String() string {
	return proto.EnumName(InviteStatus_name, int32(x))
}
func (InviteStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ResellerId string `protobuf:"bytes,3,opt,name=reseller_id,json=resellerId" json:"reseller_id,omitempty"`
	Mode       Mode   `protobuf:"varint,4,opt,name=mode,enum=organisations.Mode" json:"mode,omitempty"`
	Region     Region `protobuf:"varint,5,opt,name=region,enum=organisations.Region" json:"region,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetResellerId() string {
	if m != nil {
		return m.ResellerId
	}
	return ""
}

func (m *CreateRequest) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_SANDBOX
}

func (m *CreateRequest) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region_GLOBAL
}

type RetrieveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RetrieveRequest) Reset()                    { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()               {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RetrieveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type OrganisationResponse struct {
	Id         string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ResellerId string                     `protobuf:"bytes,3,opt,name=reseller_id,json=resellerId" json:"reseller_id,omitempty"`
	Mode       Mode                       `protobuf:"varint,4,opt,name=mode,enum=organisations.Mode" json:"mode,omitempty"`
	Region     Region                     `protobuf:"varint,5,opt,name=region,enum=organisations.Region" json:"region,omitempty"`
	Created    *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created" json:"created,omitempty"`
}

func (m *OrganisationResponse) Reset()                    { *m = OrganisationResponse{} }
func (m *OrganisationResponse) String() string            { return proto.CompactTextString(m) }
func (*OrganisationResponse) ProtoMessage()               {}
func (*OrganisationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrganisationResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrganisationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrganisationResponse) GetResellerId() string {
	if m != nil {
		return m.ResellerId
	}
	return ""
}

func (m *OrganisationResponse) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_SANDBOX
}

func (m *OrganisationResponse) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region_GLOBAL
}

func (m *OrganisationResponse) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type AddMemberRequest struct {
	MemberId       string                     `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	OrganisationId string                     `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
	Type           MemberType                 `protobuf:"varint,3,opt,name=type,enum=organisations.MemberType" json:"type,omitempty"`
	Expiry         *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *AddMemberRequest) Reset()                    { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()               {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *AddMemberRequest) GetOrganisationId() string {
	if m != nil {
		return m.OrganisationId
	}
	return ""
}

func (m *AddMemberRequest) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *AddMemberRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type RemoveMemberRequest struct {
	MemberId       string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	OrganisationId string `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
}

func (m *RemoveMemberRequest) Reset()                    { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()               {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *RemoveMemberRequest) GetOrganisationId() string {
	if m != nil {
		return m.OrganisationId
	}
	return ""
}

type InviteRequest struct {
	Email          string                     `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	OrganisationId string                     `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
	Type           MemberType                 `protobuf:"varint,3,opt,name=type,enum=organisations.MemberType" json:"type,omitempty"`
	Expiry         *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *InviteRequest) Reset()                    { *m = InviteRequest{} }
func (m *InviteRequest) String() string            { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()               {}
func (*InviteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteRequest) GetOrganisationId() string {
	if m != nil {
		return m.OrganisationId
	}
	return ""
}

func (m *InviteRequest) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *InviteRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type InviteStatusResponse struct {
	Email        string                     `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Status       InviteStatus               `protobuf:"varint,2,opt,name=status,enum=organisations.InviteStatus" json:"status,omitempty"`
	Verification string                     `protobuf:"bytes,3,opt,name=verification" json:"verification,omitempty"`
	Created      *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	Actioned     *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=actioned" json:"actioned,omitempty"`
}

func (m *InviteStatusResponse) Reset()                    { *m = InviteStatusResponse{} }
func (m *InviteStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*InviteStatusResponse) ProtoMessage()               {}
func (*InviteStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InviteStatusResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteStatusResponse) GetStatus() InviteStatus {
	if m != nil {
		return m.Status
	}
	return InviteStatus_PENDING
}

func (m *InviteStatusResponse) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

func (m *InviteStatusResponse) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *InviteStatusResponse) GetActioned() *google_protobuf.Timestamp {
	if m != nil {
		return m.Actioned
	}
	return nil
}

type ActionInviteRequest struct {
	Email          string       `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	OrganisationId string       `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
	MemberId       string       `protobuf:"bytes,3,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	Status         InviteStatus `protobuf:"varint,4,opt,name=status,enum=organisations.InviteStatus" json:"status,omitempty"`
	Verification   string       `protobuf:"bytes,5,opt,name=verification" json:"verification,omitempty"`
}

func (m *ActionInviteRequest) Reset()                    { *m = ActionInviteRequest{} }
func (m *ActionInviteRequest) String() string            { return proto.CompactTextString(m) }
func (*ActionInviteRequest) ProtoMessage()               {}
func (*ActionInviteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ActionInviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ActionInviteRequest) GetOrganisationId() string {
	if m != nil {
		return m.OrganisationId
	}
	return ""
}

func (m *ActionInviteRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *ActionInviteRequest) GetStatus() InviteStatus {
	if m != nil {
		return m.Status
	}
	return InviteStatus_PENDING
}

func (m *ActionInviteRequest) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

type MemberStatusResponse struct {
	MemberId       string                     `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	OrganisationId string                     `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
	Type           MemberType                 `protobuf:"varint,3,opt,name=type,enum=organisations.MemberType" json:"type,omitempty"`
	Invited        *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=invited" json:"invited,omitempty"`
	Expiry         *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=expiry" json:"expiry,omitempty"`
	Joined         *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=joined" json:"joined,omitempty"`
	Detached       *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=detached" json:"detached,omitempty"`
}

func (m *MemberStatusResponse) Reset()                    { *m = MemberStatusResponse{} }
func (m *MemberStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*MemberStatusResponse) ProtoMessage()               {}
func (*MemberStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MemberStatusResponse) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *MemberStatusResponse) GetOrganisationId() string {
	if m != nil {
		return m.OrganisationId
	}
	return ""
}

func (m *MemberStatusResponse) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *MemberStatusResponse) GetInvited() *google_protobuf.Timestamp {
	if m != nil {
		return m.Invited
	}
	return nil
}

func (m *MemberStatusResponse) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *MemberStatusResponse) GetJoined() *google_protobuf.Timestamp {
	if m != nil {
		return m.Joined
	}
	return nil
}

func (m *MemberStatusResponse) GetDetached() *google_protobuf.Timestamp {
	if m != nil {
		return m.Detached
	}
	return nil
}

type GetMembersRequest struct {
	OrganisationId string `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId" json:"organisation_id,omitempty"`
}

func (m *GetMembersRequest) Reset()                    { *m = GetMembersRequest{} }
func (m *GetMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMembersRequest) ProtoMessage()               {}
func (*GetMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetMembersRequest) GetOrganisationId() string {
	if m != nil {
		return m.OrganisationId
	}
	return ""
}

type GetOrganisationsRequest struct {
	MemberId string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *GetOrganisationsRequest) Reset()                    { *m = GetOrganisationsRequest{} }
func (m *GetOrganisationsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrganisationsRequest) ProtoMessage()               {}
func (*GetOrganisationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetOrganisationsRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type MembersResponse struct {
	Members map[string]*MemberStatusResponse `protobuf:"bytes,1,rep,name=members" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MembersResponse) Reset()                    { *m = MembersResponse{} }
func (m *MembersResponse) String() string            { return proto.CompactTextString(m) }
func (*MembersResponse) ProtoMessage()               {}
func (*MembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MembersResponse) GetMembers() map[string]*MemberStatusResponse {
	if m != nil {
		return m.Members
	}
	return nil
}

type OrganisationsResponse struct {
	Organisations map[string]*OrganisationResponse `protobuf:"bytes,1,rep,name=organisations" json:"organisations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *OrganisationsResponse) Reset()                    { *m = OrganisationsResponse{} }
func (m *OrganisationsResponse) String() string            { return proto.CompactTextString(m) }
func (*OrganisationsResponse) ProtoMessage()               {}
func (*OrganisationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OrganisationsResponse) GetOrganisations() map[string]*OrganisationResponse {
	if m != nil {
		return m.Organisations
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "organisations.CreateRequest")
	proto.RegisterType((*RetrieveRequest)(nil), "organisations.RetrieveRequest")
	proto.RegisterType((*OrganisationResponse)(nil), "organisations.OrganisationResponse")
	proto.RegisterType((*AddMemberRequest)(nil), "organisations.AddMemberRequest")
	proto.RegisterType((*RemoveMemberRequest)(nil), "organisations.RemoveMemberRequest")
	proto.RegisterType((*InviteRequest)(nil), "organisations.InviteRequest")
	proto.RegisterType((*InviteStatusResponse)(nil), "organisations.InviteStatusResponse")
	proto.RegisterType((*ActionInviteRequest)(nil), "organisations.ActionInviteRequest")
	proto.RegisterType((*MemberStatusResponse)(nil), "organisations.MemberStatusResponse")
	proto.RegisterType((*GetMembersRequest)(nil), "organisations.GetMembersRequest")
	proto.RegisterType((*GetOrganisationsRequest)(nil), "organisations.GetOrganisationsRequest")
	proto.RegisterType((*MembersResponse)(nil), "organisations.MembersResponse")
	proto.RegisterType((*OrganisationsResponse)(nil), "organisations.OrganisationsResponse")
	proto.RegisterEnum("organisations.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("organisations.Region", Region_name, Region_value)
	proto.RegisterEnum("organisations.MemberType", MemberType_name, MemberType_value)
	proto.RegisterEnum("organisations.InviteStatus", InviteStatus_name, InviteStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Organisations service

type OrganisationsClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*OrganisationResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*OrganisationResponse, error)
	GetOrganisations(ctx context.Context, in *GetOrganisationsRequest, opts ...grpc.CallOption) (*OrganisationsResponse, error)
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error)
	Invite(ctx context.Context, in *InviteRequest, opts ...grpc.CallOption) (*InviteStatusResponse, error)
	ActionInvite(ctx context.Context, in *ActionInviteRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
}

type organisationsClient struct {
	cc *grpc.ClientConn
}

func NewOrganisationsClient(cc *grpc.ClientConn) OrganisationsClient {
	return &organisationsClient{cc}
}

func (c *organisationsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*OrganisationResponse, error) {
	out := new(OrganisationResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*OrganisationResponse, error) {
	out := new(OrganisationResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) GetOrganisations(ctx context.Context, in *GetOrganisationsRequest, opts ...grpc.CallOption) (*OrganisationsResponse, error) {
	out := new(OrganisationsResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/GetOrganisations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/AddMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/RemoveMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error) {
	out := new(MembersResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/GetMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) Invite(ctx context.Context, in *InviteRequest, opts ...grpc.CallOption) (*InviteStatusResponse, error) {
	out := new(InviteStatusResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/Invite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organisationsClient) ActionInvite(ctx context.Context, in *ActionInviteRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/organisations.Organisations/ActionInvite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Organisations service

type OrganisationsServer interface {
	Create(context.Context, *CreateRequest) (*OrganisationResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*OrganisationResponse, error)
	GetOrganisations(context.Context, *GetOrganisationsRequest) (*OrganisationsResponse, error)
	AddMember(context.Context, *AddMemberRequest) (*MemberStatusResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*MemberStatusResponse, error)
	GetMembers(context.Context, *GetMembersRequest) (*MembersResponse, error)
	Invite(context.Context, *InviteRequest) (*InviteStatusResponse, error)
	ActionInvite(context.Context, *ActionInviteRequest) (*MemberStatusResponse, error)
}

func RegisterOrganisationsServer(s *grpc.Server, srv OrganisationsServer) {
	s.RegisterService(&_Organisations_serviceDesc, srv)
}

func _Organisations_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_GetOrganisations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganisationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).GetOrganisations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/GetOrganisations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).GetOrganisations(ctx, req.(*GetOrganisationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/GetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).GetMembers(ctx, req.(*GetMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/Invite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).Invite(ctx, req.(*InviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organisations_ActionInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganisationsServer).ActionInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organisations.Organisations/ActionInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganisationsServer).ActionInvite(ctx, req.(*ActionInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Organisations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "organisations.Organisations",
	HandlerType: (*OrganisationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Organisations_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Organisations_Retrieve_Handler,
		},
		{
			MethodName: "GetOrganisations",
			Handler:    _Organisations_GetOrganisations_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _Organisations_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _Organisations_RemoveMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _Organisations_GetMembers_Handler,
		},
		{
			MethodName: "Invite",
			Handler:    _Organisations_Invite_Handler,
		},
		{
			MethodName: "ActionInvite",
			Handler:    _Organisations_ActionInvite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organisations.proto",
}

func init() { proto.RegisterFile("organisations.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x57, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xee, 0xe4, 0x9e, 0x93, 0x4b, 0xcd, 0xb4, 0x2b, 0x42, 0x16, 0x6d, 0x83, 0x17, 0x41, 0xe9,
	0xaa, 0xa9, 0xe4, 0x5d, 0x2d, 0x17, 0xed, 0x4b, 0x9a, 0x98, 0x2a, 0xb0, 0x8d, 0xc3, 0x24, 0xa1,
	0x2b, 0x10, 0x2a, 0x6e, 0x3c, 0xcd, 0x0e, 0xc4, 0x71, 0xb0, 0x9d, 0x88, 0xfc, 0x27, 0x5e, 0xf6,
	0x11, 0xf1, 0x0f, 0xf8, 0x0f, 0x3c, 0xf0, 0xc8, 0x33, 0x7f, 0x00, 0x79, 0x6c, 0xa7, 0xbe, 0x6d,
	0x31, 0x08, 0xb4, 0xfb, 0x96, 0x39, 0xf3, 0x9d, 0xe3, 0x73, 0xf9, 0xe6, 0x9c, 0x13, 0xd8, 0x33,
	0xcc, 0x99, 0xba, 0x60, 0x96, 0x6a, 0x33, 0x63, 0x61, 0xb5, 0x97, 0xa6, 0x61, 0x1b, 0xb8, 0x16,
	0x12, 0x36, 0x0f, 0x66, 0x86, 0x31, 0x9b, 0xd3, 0x13, 0x7e, 0x79, 0xb5, 0xba, 0x3e, 0xb1, 0x99,
	0x4e, 0x2d, 0x5b, 0xd5, 0x97, 0x2e, 0x5e, 0xfc, 0x09, 0x41, 0xad, 0x6b, 0x52, 0xd5, 0xa6, 0x84,
	0xfe, 0xb0, 0xa2, 0x96, 0x8d, 0xeb, 0x90, 0x61, 0x5a, 0x03, 0xb5, 0xd0, 0x61, 0x99, 0x64, 0x98,
	0x86, 0x31, 0xe4, 0x16, 0xaa, 0x4e, 0x1b, 0x19, 0x2e, 0xe1, 0xbf, 0xf1, 0x01, 0x54, 0x4c, 0x6a,
	0xd1, 0xf9, 0x9c, 0x9a, 0x97, 0x4c, 0x6b, 0x64, 0xf9, 0x15, 0xf8, 0xa2, 0xbe, 0x86, 0xdf, 0x87,
	0x9c, 0x6e, 0x68, 0xb4, 0x91, 0x6b, 0xa1, 0xc3, 0xba, 0xb4, 0xd7, 0x0e, 0xbb, 0x7a, 0x6e, 0x68,
	0x94, 0x70, 0x00, 0x3e, 0x86, 0x82, 0x49, 0x67, 0xcc, 0x58, 0x34, 0xf2, 0x1c, 0x7a, 0x27, 0x02,
	0x25, 0xfc, 0x92, 0x78, 0x20, 0xf1, 0x1d, 0xd8, 0x25, 0xd4, 0x36, 0x19, 0x5d, 0xbf, 0xcc, 0x5f,
	0xf1, 0x0f, 0x04, 0xfb, 0x4a, 0xc0, 0x06, 0xa1, 0xd6, 0xd2, 0x58, 0x58, 0xf4, 0xb5, 0x0e, 0x0c,
	0x3f, 0x82, 0xe2, 0x94, 0x97, 0x41, 0x6b, 0x14, 0x5a, 0xe8, 0xb0, 0x22, 0x35, 0xdb, 0x6e, 0xe9,
	0xda, 0x7e, 0xe9, 0xda, 0x63, 0xbf, 0x74, 0xc4, 0x87, 0x8a, 0xbf, 0x20, 0x10, 0x3a, 0x9a, 0x76,
	0x4e, 0xf5, 0x2b, 0x6a, 0xfa, 0x09, 0xb9, 0x0b, 0x65, 0x9d, 0x0b, 0x2e, 0xb7, 0xe1, 0x96, 0x5c,
	0x01, 0xf7, 0x7f, 0x37, 0xe8, 0x87, 0x03, 0x71, 0xe3, 0xaf, 0x07, 0xc5, 0x7d, 0x0d, 0x1f, 0x43,
	0xce, 0xde, 0x2c, 0x29, 0x4f, 0x41, 0x5d, 0x7a, 0x2b, 0x1a, 0x28, 0xb7, 0x37, 0xde, 0x2c, 0x29,
	0xe1, 0x30, 0x2c, 0x41, 0x81, 0xfe, 0xb8, 0x64, 0xe6, 0x86, 0x67, 0xe6, 0x76, 0xf7, 0x3d, 0xa4,
	0xf8, 0x35, 0xec, 0x11, 0xaa, 0x1b, 0x6b, 0xfa, 0x3f, 0xf8, 0x2f, 0xbe, 0x40, 0x50, 0xeb, 0x2f,
	0xd6, 0xec, 0x86, 0xd8, 0xfb, 0x90, 0xa7, 0xba, 0xca, 0xe6, 0x9e, 0x4d, 0xf7, 0xf0, 0x5a, 0x25,
	0xe4, 0x4f, 0x04, 0xfb, 0xae, 0xcf, 0x23, 0x5b, 0xb5, 0x57, 0xd6, 0x96, 0xba, 0xc9, 0xae, 0x3f,
	0x84, 0x82, 0xc5, 0x71, 0xdc, 0xe3, 0xba, 0x74, 0x37, 0xe2, 0x53, 0xc8, 0x94, 0x07, 0xc5, 0x22,
	0x54, 0xd7, 0xd4, 0x64, 0xd7, 0x6c, 0xca, 0x51, 0x1e, 0xc5, 0x43, 0xb2, 0x20, 0x19, 0x73, 0xa9,
	0xc9, 0x88, 0x1f, 0x43, 0x49, 0x9d, 0x3a, 0xfa, 0x54, 0xe3, 0x9c, 0xbf, 0x5d, 0x6d, 0x8b, 0x15,
	0x7f, 0x45, 0xb0, 0xd7, 0xe1, 0x87, 0xff, 0xb4, 0x5e, 0x21, 0x1a, 0x65, 0x23, 0x34, 0xba, 0x49,
	0x5d, 0xee, 0xdf, 0xa7, 0x2e, 0x1f, 0x4f, 0x9d, 0xf8, 0x7b, 0x06, 0xf6, 0x5d, 0x2e, 0x44, 0x4a,
	0xf8, 0x4a, 0x5e, 0xe5, 0x23, 0x28, 0x32, 0x1e, 0x49, 0xaa, 0x42, 0x7a, 0xd0, 0x00, 0x75, 0xf3,
	0x69, 0xa9, 0xeb, 0xe8, 0x7c, 0x67, 0xb0, 0x45, 0xaa, 0xf6, 0xe5, 0x21, 0x1d, 0xc2, 0x68, 0xd4,
	0x56, 0xa7, 0xcf, 0xa9, 0xd6, 0x28, 0xfe, 0x3d, 0x61, 0x7c, 0xac, 0xf8, 0x04, 0xde, 0x38, 0xa3,
	0xb6, 0x1b, 0xac, 0xe5, 0xb3, 0x25, 0x21, 0x85, 0x28, 0xb1, 0x31, 0x3c, 0x86, 0x37, 0xcf, 0xa8,
	0x1d, 0x9c, 0x10, 0x56, 0x9a, 0xce, 0x23, 0xfe, 0x8c, 0x60, 0x77, 0xfb, 0x4d, 0xaf, 0xa8, 0x32,
	0x14, 0xdd, 0x7b, 0xab, 0x81, 0x5a, 0xd9, 0xc3, 0x8a, 0xf4, 0x20, 0xb1, 0x22, 0x5b, 0x05, 0xff,
	0x2c, 0x2f, 0x6c, 0x73, 0x43, 0x7c, 0xdd, 0xe6, 0x25, 0x54, 0x83, 0x17, 0x58, 0x80, 0xec, 0xf7,
	0x74, 0xe3, 0x79, 0xe0, 0xfc, 0xc4, 0x1f, 0x43, 0x7e, 0xad, 0xce, 0x57, 0xee, 0xb0, 0xaa, 0x48,
	0xf7, 0x13, 0x3f, 0x13, 0x66, 0x1c, 0x71, 0x35, 0x3e, 0xc9, 0x7c, 0x84, 0xc4, 0xdf, 0x10, 0xdc,
	0x89, 0x44, 0xec, 0x45, 0xf0, 0x0d, 0x84, 0x37, 0x06, 0x2f, 0x8e, 0x0f, 0x23, 0x1f, 0x48, 0x54,
	0x0e, 0x4b, 0xdd, 0x98, 0x22, 0xfb, 0x07, 0x05, 0x1c, 0x07, 0xfd, 0xf3, 0xf8, 0x92, 0xe6, 0x79,
	0x20, 0xbe, 0xa3, 0xfb, 0x90, 0x73, 0x46, 0x2f, 0xae, 0x40, 0x71, 0xd4, 0x19, 0xf4, 0x4e, 0x95,
	0x67, 0xc2, 0x0e, 0xae, 0x03, 0x0c, 0x89, 0xd2, 0x9b, 0x74, 0xc7, 0x7d, 0x65, 0x20, 0xa0, 0x23,
	0x09, 0x0a, 0xee, 0xd0, 0xc5, 0x00, 0x85, 0xb3, 0xa7, 0xca, 0x69, 0xe7, 0xa9, 0xb0, 0x83, 0x0b,
	0x90, 0x99, 0x8c, 0x04, 0xe4, 0xc8, 0xe4, 0x09, 0x51, 0x86, 0xb2, 0x90, 0xc1, 0x25, 0xc8, 0x75,
	0x46, 0xfd, 0x8e, 0x90, 0x3d, 0x7a, 0x02, 0x70, 0xf3, 0xa8, 0x70, 0x19, 0xf2, 0xca, 0xc5, 0x40,
	0x26, 0xc2, 0x8e, 0x03, 0x3f, 0x97, 0xcf, 0x4f, 0x65, 0xe2, 0xaa, 0x7e, 0xd9, 0x97, 0x2f, 0x64,
	0x22, 0x64, 0xb8, 0x07, 0x93, 0xe1, 0x50, 0x21, 0x63, 0x21, 0x7b, 0x34, 0x82, 0x6a, 0xb0, 0x91,
	0x38, 0x97, 0x43, 0x79, 0xd0, 0xeb, 0x0f, 0xce, 0x84, 0x1d, 0x5c, 0x85, 0x52, 0xa7, 0xdb, 0x95,
	0x87, 0x63, 0xb9, 0x27, 0x20, 0xe7, 0x44, 0xe4, 0xcf, 0xe4, 0xae, 0x73, 0xe2, 0x56, 0xe4, 0x67,
	0xc3, 0x3e, 0x91, 0x7b, 0x42, 0x16, 0xd7, 0xa0, 0x3c, 0x50, 0xc6, 0x97, 0x9f, 0x2a, 0x93, 0x41,
	0x4f, 0xc8, 0x49, 0x2f, 0xf2, 0x50, 0x0b, 0xe5, 0x14, 0x7f, 0x0e, 0x05, 0x77, 0x85, 0xc3, 0x6f,
	0x47, 0xf2, 0x16, 0xda, 0xec, 0x9a, 0x69, 0xb2, 0x8a, 0x15, 0x28, 0xf9, 0x1b, 0x16, 0xbe, 0x17,
	0xdb, 0x59, 0x42, 0xab, 0x57, 0x3a, 0x83, 0xdf, 0x82, 0x10, 0x7d, 0x6f, 0xf8, 0xbd, 0x88, 0xe2,
	0x4b, 0x1e, 0x64, 0xf3, 0xdd, 0x34, 0x34, 0xc4, 0x5f, 0x40, 0x79, 0xbb, 0x04, 0xe1, 0x83, 0x88,
	0x4a, 0x74, 0x3d, 0x6a, 0xa6, 0x79, 0x3b, 0xf8, 0x02, 0xaa, 0xc1, 0xd5, 0x04, 0x8b, 0xb1, 0x4c,
	0xc4, 0xf6, 0x96, 0x74, 0x86, 0x07, 0x00, 0x37, 0xbd, 0x0b, 0xb7, 0xe2, 0x79, 0x08, 0xb7, 0xb5,
	0xe6, 0xbd, 0xdb, 0x1b, 0x8a, 0x53, 0x7b, 0x97, 0x62, 0xb1, 0xda, 0x87, 0x86, 0x69, 0xcc, 0xb9,
	0xc4, 0x35, 0xe3, 0x02, 0xaa, 0xc1, 0x41, 0x1c, 0x8b, 0x3a, 0x61, 0x4a, 0xa7, 0x8a, 0xfa, 0xf4,
	0xc1, 0x57, 0x1f, 0xcc, 0x98, 0xfd, 0x7c, 0x75, 0xd5, 0x9e, 0x1a, 0xfa, 0xc9, 0xb5, 0x61, 0xda,
	0xec, 0x9a, 0xb9, 0x7f, 0x4a, 0x8e, 0x67, 0xc6, 0x49, 0xc8, 0xc2, 0x55, 0x81, 0xcb, 0x1f, 0xfe,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xa6, 0x9b, 0x7d, 0xe0, 0x0c, 0x00, 0x00,
}
