// Code generated by protoc-gen-go.
// source: fdl.proto
// DO NOT EDIT!

/*
Package fdl is a generated protocol buffer package.

It is generated from these files:
	fdl.proto

It has these top-level messages:
	Property
	ReadProperty
	MutationRequest
	ReadRequest
	MutationResponse
	PropertiesResponse
	ListAddRequest
	KeyRequest
	ListItemResponse
	ListItemsResponse
	ListRangeRequest
*/
package fdl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import fcommon "github.com/fortifi/proto-go/fcommon"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PropertyType int32

const (
	PropertyType_META    PropertyType = 0
	PropertyType_DATA    PropertyType = 1
	PropertyType_COUNTER PropertyType = 2
	PropertyType_SET     PropertyType = 3
	PropertyType_LIST    PropertyType = 4
)

var PropertyType_name = map[int32]string{
	0: "META",
	1: "DATA",
	2: "COUNTER",
	3: "SET",
	4: "LIST",
}
var PropertyType_value = map[string]int32{
	"META":    0,
	"DATA":    1,
	"COUNTER": 2,
	"SET":     3,
	"LIST":    4,
}

func (x PropertyType) String() string {
	return proto.EnumName(PropertyType_name, int32(x))
}
func (PropertyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MutationMode int32

const (
	MutationMode_NONE   MutationMode = 0
	MutationMode_WRITE  MutationMode = 1
	MutationMode_APPEND MutationMode = 2
	MutationMode_REMOVE MutationMode = 3
	MutationMode_DELETE MutationMode = 4
)

var MutationMode_name = map[int32]string{
	0: "NONE",
	1: "WRITE",
	2: "APPEND",
	3: "REMOVE",
	4: "DELETE",
}
var MutationMode_value = map[string]int32{
	"NONE":   0,
	"WRITE":  1,
	"APPEND": 2,
	"REMOVE": 3,
	"DELETE": 4,
}

func (x MutationMode) String() string {
	return proto.EnumName(MutationMode_name, int32(x))
}
func (MutationMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MutationStatus int32

const (
	MutationStatus_FAILURE MutationStatus = 0
	MutationStatus_SUCCESS MutationStatus = 1
)

var MutationStatus_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
}
var MutationStatus_value = map[string]int32{
	"FAILURE": 0,
	"SUCCESS": 1,
}

func (x MutationStatus) String() string {
	return proto.EnumName(MutationStatus_name, int32(x))
}
func (MutationStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Property struct {
	Property string       `protobuf:"bytes,1,opt,name=property" json:"property,omitempty"`
	Type     PropertyType `protobuf:"varint,2,opt,name=type,enum=fdl.PropertyType" json:"type,omitempty"`
	Value    string       `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Mode     MutationMode `protobuf:"varint,4,opt,name=mode,enum=fdl.MutationMode" json:"mode,omitempty"`
	Index    bool         `protobuf:"varint,5,opt,name=index" json:"index,omitempty"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Property) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *Property) GetType() PropertyType {
	if m != nil {
		return m.Type
	}
	return PropertyType_META
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Property) GetMode() MutationMode {
	if m != nil {
		return m.Mode
	}
	return MutationMode_NONE
}

func (m *Property) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

type ReadProperty struct {
	Property string       `protobuf:"bytes,1,opt,name=property" json:"property,omitempty"`
	Type     PropertyType `protobuf:"varint,2,opt,name=type,enum=fdl.PropertyType" json:"type,omitempty"`
	IsPrefix bool         `protobuf:"varint,3,opt,name=is_prefix,json=isPrefix" json:"is_prefix,omitempty"`
}

func (m *ReadProperty) Reset()                    { *m = ReadProperty{} }
func (m *ReadProperty) String() string            { return proto.CompactTextString(m) }
func (*ReadProperty) ProtoMessage()               {}
func (*ReadProperty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadProperty) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *ReadProperty) GetType() PropertyType {
	if m != nil {
		return m.Type
	}
	return PropertyType_META
}

func (m *ReadProperty) GetIsPrefix() bool {
	if m != nil {
		return m.IsPrefix
	}
	return false
}

type MutationRequest struct {
	Fid        string      `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	Properties []*Property `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
	MemberId   string      `protobuf:"bytes,3,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *MutationRequest) Reset()                    { *m = MutationRequest{} }
func (m *MutationRequest) String() string            { return proto.CompactTextString(m) }
func (*MutationRequest) ProtoMessage()               {}
func (*MutationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MutationRequest) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *MutationRequest) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *MutationRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type ReadRequest struct {
	Fid        string          `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	Properties []*ReadProperty `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
	MemberId   string          `protobuf:"bytes,3,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *ReadRequest) GetProperties() []*ReadProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ReadRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type MutationResponse struct {
	Fid           string         `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	Status        MutationStatus `protobuf:"varint,2,opt,name=status,enum=fdl.MutationStatus" json:"status,omitempty"`
	StatusMessage string         `protobuf:"bytes,3,opt,name=status_message,json=statusMessage" json:"status_message,omitempty"`
}

func (m *MutationResponse) Reset()                    { *m = MutationResponse{} }
func (m *MutationResponse) String() string            { return proto.CompactTextString(m) }
func (*MutationResponse) ProtoMessage()               {}
func (*MutationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MutationResponse) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *MutationResponse) GetStatus() MutationStatus {
	if m != nil {
		return m.Status
	}
	return MutationStatus_FAILURE
}

func (m *MutationResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type PropertiesResponse struct {
	Fid        string      `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	Properties []*Property `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
}

func (m *PropertiesResponse) Reset()                    { *m = PropertiesResponse{} }
func (m *PropertiesResponse) String() string            { return proto.CompactTextString(m) }
func (*PropertiesResponse) ProtoMessage()               {}
func (*PropertiesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PropertiesResponse) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *PropertiesResponse) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ListAddRequest struct {
	Fid      string `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	ListName string `protobuf:"bytes,2,opt,name=list_name,json=listName" json:"list_name,omitempty"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value    string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	MemberId string `protobuf:"bytes,5,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *ListAddRequest) Reset()                    { *m = ListAddRequest{} }
func (m *ListAddRequest) String() string            { return proto.CompactTextString(m) }
func (*ListAddRequest) ProtoMessage()               {}
func (*ListAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListAddRequest) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *ListAddRequest) GetListName() string {
	if m != nil {
		return m.ListName
	}
	return ""
}

func (m *ListAddRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListAddRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ListAddRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type KeyRequest struct {
	Fid      string `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	ListName string `protobuf:"bytes,2,opt,name=list_name,json=listName" json:"list_name,omitempty"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	MemberId string `protobuf:"bytes,4,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *KeyRequest) Reset()                    { *m = KeyRequest{} }
func (m *KeyRequest) String() string            { return proto.CompactTextString(m) }
func (*KeyRequest) ProtoMessage()               {}
func (*KeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *KeyRequest) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *KeyRequest) GetListName() string {
	if m != nil {
		return m.ListName
	}
	return ""
}

func (m *KeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type ListItemResponse struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ListItemResponse) Reset()                    { *m = ListItemResponse{} }
func (m *ListItemResponse) String() string            { return proto.CompactTextString(m) }
func (*ListItemResponse) ProtoMessage()               {}
func (*ListItemResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListItemResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListItemResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ListItemsResponse struct {
	Fid      string              `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	ListName string              `protobuf:"bytes,2,opt,name=list_name,json=listName" json:"list_name,omitempty"`
	Items    []*ListItemResponse `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (m *ListItemsResponse) Reset()                    { *m = ListItemsResponse{} }
func (m *ListItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListItemsResponse) ProtoMessage()               {}
func (*ListItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListItemsResponse) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *ListItemsResponse) GetListName() string {
	if m != nil {
		return m.ListName
	}
	return ""
}

func (m *ListItemsResponse) GetItems() []*ListItemResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListRangeRequest struct {
	Fid      string `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	ListName string `protobuf:"bytes,2,opt,name=list_name,json=listName" json:"list_name,omitempty"`
	StartKey string `protobuf:"bytes,3,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey   string `protobuf:"bytes,4,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	Limit    int32  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	MemberId string `protobuf:"bytes,6,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *ListRangeRequest) Reset()                    { *m = ListRangeRequest{} }
func (m *ListRangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRangeRequest) ProtoMessage()               {}
func (*ListRangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListRangeRequest) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *ListRangeRequest) GetListName() string {
	if m != nil {
		return m.ListName
	}
	return ""
}

func (m *ListRangeRequest) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *ListRangeRequest) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *ListRangeRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRangeRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func init() {
	proto.RegisterType((*Property)(nil), "fdl.Property")
	proto.RegisterType((*ReadProperty)(nil), "fdl.ReadProperty")
	proto.RegisterType((*MutationRequest)(nil), "fdl.MutationRequest")
	proto.RegisterType((*ReadRequest)(nil), "fdl.ReadRequest")
	proto.RegisterType((*MutationResponse)(nil), "fdl.MutationResponse")
	proto.RegisterType((*PropertiesResponse)(nil), "fdl.PropertiesResponse")
	proto.RegisterType((*ListAddRequest)(nil), "fdl.ListAddRequest")
	proto.RegisterType((*KeyRequest)(nil), "fdl.KeyRequest")
	proto.RegisterType((*ListItemResponse)(nil), "fdl.ListItemResponse")
	proto.RegisterType((*ListItemsResponse)(nil), "fdl.ListItemsResponse")
	proto.RegisterType((*ListRangeRequest)(nil), "fdl.ListRangeRequest")
	proto.RegisterEnum("fdl.PropertyType", PropertyType_name, PropertyType_value)
	proto.RegisterEnum("fdl.MutationMode", MutationMode_name, MutationMode_value)
	proto.RegisterEnum("fdl.MutationStatus", MutationStatus_name, MutationStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Fdl service

type FdlClient interface {
	Mutate(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*PropertiesResponse, error)
	ListAdd(ctx context.Context, in *ListAddRequest, opts ...grpc.CallOption) (*fcommon.BoolResponse, error)
	ListRemove(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*fcommon.BoolResponse, error)
	ListRetrieveItem(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*ListItemResponse, error)
	ListRange(ctx context.Context, in *ListRangeRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
}

type fdlClient struct {
	cc *grpc.ClientConn
}

func NewFdlClient(cc *grpc.ClientConn) FdlClient {
	return &fdlClient{cc}
}

func (c *fdlClient) Mutate(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	out := new(MutationResponse)
	err := grpc.Invoke(ctx, "/fdl.Fdl/Mutate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fdlClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*PropertiesResponse, error) {
	out := new(PropertiesResponse)
	err := grpc.Invoke(ctx, "/fdl.Fdl/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fdlClient) ListAdd(ctx context.Context, in *ListAddRequest, opts ...grpc.CallOption) (*fcommon.BoolResponse, error) {
	out := new(fcommon.BoolResponse)
	err := grpc.Invoke(ctx, "/fdl.Fdl/ListAdd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fdlClient) ListRemove(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*fcommon.BoolResponse, error) {
	out := new(fcommon.BoolResponse)
	err := grpc.Invoke(ctx, "/fdl.Fdl/ListRemove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fdlClient) ListRetrieveItem(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*ListItemResponse, error) {
	out := new(ListItemResponse)
	err := grpc.Invoke(ctx, "/fdl.Fdl/ListRetrieveItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fdlClient) ListRange(ctx context.Context, in *ListRangeRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	out := new(ListItemsResponse)
	err := grpc.Invoke(ctx, "/fdl.Fdl/ListRange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fdl service

type FdlServer interface {
	Mutate(context.Context, *MutationRequest) (*MutationResponse, error)
	Read(context.Context, *ReadRequest) (*PropertiesResponse, error)
	ListAdd(context.Context, *ListAddRequest) (*fcommon.BoolResponse, error)
	ListRemove(context.Context, *KeyRequest) (*fcommon.BoolResponse, error)
	ListRetrieveItem(context.Context, *KeyRequest) (*ListItemResponse, error)
	ListRange(context.Context, *ListRangeRequest) (*ListItemsResponse, error)
}

func RegisterFdlServer(s *grpc.Server, srv FdlServer) {
	s.RegisterService(&_Fdl_serviceDesc, srv)
}

func _Fdl_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FdlServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdl.Fdl/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FdlServer).Mutate(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fdl_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FdlServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdl.Fdl/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FdlServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fdl_ListAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FdlServer).ListAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdl.Fdl/ListAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FdlServer).ListAdd(ctx, req.(*ListAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fdl_ListRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FdlServer).ListRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdl.Fdl/ListRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FdlServer).ListRemove(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fdl_ListRetrieveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FdlServer).ListRetrieveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdl.Fdl/ListRetrieveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FdlServer).ListRetrieveItem(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fdl_ListRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FdlServer).ListRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdl.Fdl/ListRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FdlServer).ListRange(ctx, req.(*ListRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fdl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fdl.Fdl",
	HandlerType: (*FdlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mutate",
			Handler:    _Fdl_Mutate_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Fdl_Read_Handler,
		},
		{
			MethodName: "ListAdd",
			Handler:    _Fdl_ListAdd_Handler,
		},
		{
			MethodName: "ListRemove",
			Handler:    _Fdl_ListRemove_Handler,
		},
		{
			MethodName: "ListRetrieveItem",
			Handler:    _Fdl_ListRetrieveItem_Handler,
		},
		{
			MethodName: "ListRange",
			Handler:    _Fdl_ListRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fdl.proto",
}

func init() { proto.RegisterFile("fdl.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 766 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0x41, 0x6f, 0xe2, 0x46,
	0x14, 0x5e, 0x63, 0x03, 0xf6, 0x23, 0x61, 0xbd, 0xb3, 0xbb, 0x5d, 0x44, 0x0e, 0xa5, 0x96, 0x56,
	0x42, 0xac, 0x92, 0x28, 0x69, 0x73, 0xc9, 0x8d, 0x24, 0x4e, 0x85, 0x02, 0x04, 0x0d, 0xa6, 0x95,
	0x7a, 0x41, 0x4e, 0x3c, 0xa6, 0xd3, 0xda, 0x1e, 0x6a, 0x0f, 0x51, 0xb8, 0xf7, 0x87, 0xf4, 0xdc,
	0xdf, 0xd3, 0x1f, 0x54, 0xcd, 0xd8, 0x80, 0x8d, 0x08, 0x6a, 0x57, 0xb9, 0xbd, 0x79, 0x33, 0x9f,
	0xbf, 0xf7, 0xbe, 0xf9, 0xde, 0x18, 0x0c, 0xdf, 0x0b, 0x4e, 0xe6, 0x31, 0xe3, 0x0c, 0xa9, 0xbe,
	0x17, 0x34, 0x0f, 0xfd, 0x47, 0x16, 0x86, 0x2c, 0x4a, 0x73, 0xd6, 0x5f, 0x0a, 0xe8, 0xa3, 0x98,
	0xcd, 0x49, 0xcc, 0x97, 0xa8, 0x09, 0xfa, 0x3c, 0x8b, 0x1b, 0x4a, 0x4b, 0x69, 0x1b, 0x78, 0xbd,
	0x46, 0x9f, 0x41, 0xe3, 0xcb, 0x39, 0x69, 0x94, 0x5a, 0x4a, 0xbb, 0x7e, 0xfe, 0xee, 0x44, 0x7c,
	0x76, 0x05, 0x74, 0x96, 0x73, 0x82, 0xe5, 0x36, 0xfa, 0x00, 0xe5, 0x27, 0x37, 0x58, 0x90, 0x86,
	0x2a, 0xf1, 0xe9, 0x42, 0x80, 0x43, 0xe6, 0x91, 0x86, 0x96, 0x03, 0x0f, 0x16, 0xdc, 0xe5, 0x94,
	0x45, 0x03, 0xe6, 0x11, 0x2c, 0xb7, 0x05, 0x98, 0x46, 0x1e, 0x79, 0x6e, 0x94, 0x5b, 0x4a, 0x5b,
	0xc7, 0xe9, 0xc2, 0x8a, 0xe0, 0x00, 0x13, 0xd7, 0x7b, 0xcd, 0x2a, 0x8f, 0xc0, 0xa0, 0xc9, 0x74,
	0x1e, 0x13, 0x9f, 0x3e, 0xcb, 0x4a, 0x75, 0xac, 0xd3, 0x64, 0x24, 0xd7, 0x16, 0x83, 0xb7, 0xab,
	0xda, 0x30, 0xf9, 0x63, 0x41, 0x12, 0x8e, 0x4c, 0x50, 0x7d, 0xea, 0x65, 0x6c, 0x22, 0x44, 0xc7,
	0x00, 0x19, 0x29, 0x25, 0x49, 0xa3, 0xd4, 0x52, 0xdb, 0xb5, 0xf3, 0xc3, 0x02, 0x1d, 0xce, 0x1d,
	0x10, 0x84, 0x21, 0x09, 0x1f, 0x48, 0x3c, 0xa5, 0x5e, 0x26, 0x8d, 0x9e, 0x26, 0x7a, 0x9e, 0xc5,
	0xa0, 0x26, 0x1a, 0x7c, 0x99, 0xec, 0x6c, 0x07, 0x59, 0xda, 0x5b, 0x5e, 0x98, 0xff, 0x4e, 0xf8,
	0x0c, 0xe6, 0xa6, 0xc3, 0x64, 0xce, 0xa2, 0x84, 0xec, 0x60, 0xfd, 0x02, 0x95, 0x84, 0xbb, 0x7c,
	0x91, 0x64, 0x6a, 0xbe, 0x2f, 0x5c, 0xdb, 0x58, 0x6e, 0xe1, 0xec, 0x08, 0xfa, 0x0c, 0xf5, 0x34,
	0x9a, 0x86, 0x24, 0x49, 0xdc, 0xd9, 0xca, 0x00, 0x87, 0x69, 0x76, 0x90, 0x26, 0xad, 0x09, 0xa0,
	0xd1, 0xba, 0xc8, 0x3d, 0xdc, 0xff, 0x4f, 0x5e, 0xeb, 0x4f, 0x05, 0xea, 0x7d, 0x9a, 0xf0, 0xae,
	0xb7, 0x47, 0xc5, 0x23, 0x30, 0x02, 0x9a, 0xf0, 0x69, 0xe4, 0x86, 0xa9, 0x41, 0x0c, 0xac, 0x8b,
	0xc4, 0xd0, 0x0d, 0x65, 0x09, 0xbf, 0x93, 0x65, 0x56, 0xb4, 0x08, 0x37, 0x4e, 0xd6, 0xf2, 0x4e,
	0x2e, 0xe8, 0x5a, 0xde, 0xd2, 0xf5, 0x37, 0x80, 0x3b, 0xb2, 0x7c, 0xb5, 0x0a, 0x0a, 0x5c, 0xda,
	0x16, 0xd7, 0x25, 0x98, 0xa2, 0xe3, 0x1e, 0x27, 0x61, 0x5e, 0x47, 0xf1, 0x09, 0x65, 0x47, 0x13,
	0xa5, 0x5c, 0x13, 0x16, 0x83, 0x77, 0x2b, 0xec, 0xbe, 0x4b, 0xd8, 0x5b, 0xee, 0x17, 0x28, 0x53,
	0x81, 0x6f, 0xa8, 0xf2, 0x72, 0x3e, 0xca, 0xcb, 0xd9, 0xae, 0x08, 0xa7, 0x67, 0xac, 0xbf, 0x95,
	0xb4, 0x5a, 0xec, 0x46, 0x33, 0xf2, 0x95, 0xfa, 0x1c, 0x81, 0x91, 0x70, 0x37, 0xe6, 0xd3, 0x8d,
	0x4a, 0xba, 0x4c, 0xdc, 0x91, 0x25, 0xfa, 0x04, 0x55, 0x12, 0x79, 0x72, 0x2b, 0x15, 0xaa, 0x42,
	0x22, 0xef, 0x2e, 0x15, 0x20, 0xa0, 0x21, 0xe5, 0xf2, 0xae, 0xca, 0x38, 0x5d, 0x14, 0x95, 0xad,
	0x14, 0x95, 0xed, 0x5c, 0xc1, 0x41, 0xfe, 0xc9, 0x40, 0x3a, 0x68, 0x03, 0xdb, 0xe9, 0x9a, 0x6f,
	0x44, 0x74, 0xd3, 0x75, 0xba, 0xa6, 0x82, 0x6a, 0x50, 0xbd, 0xbe, 0x9f, 0x0c, 0x1d, 0x1b, 0x9b,
	0x25, 0x54, 0x05, 0x75, 0x6c, 0x3b, 0xa6, 0x2a, 0xf6, 0xfb, 0xbd, 0xb1, 0x63, 0x6a, 0x9d, 0x1f,
	0xe1, 0x20, 0xff, 0xbe, 0x89, 0x9d, 0xe1, 0xfd, 0xd0, 0x36, 0xdf, 0x20, 0x03, 0xca, 0x3f, 0xe3,
	0x9e, 0x63, 0x9b, 0x0a, 0x02, 0xa8, 0x74, 0x47, 0x23, 0x7b, 0x78, 0x63, 0x96, 0x44, 0x8c, 0xed,
	0xc1, 0xfd, 0x4f, 0xb6, 0xa9, 0x8a, 0xf8, 0xc6, 0xee, 0xdb, 0x8e, 0x6d, 0x6a, 0x9d, 0x0e, 0xd4,
	0x8b, 0x13, 0x27, 0xa8, 0x6f, 0xbb, 0xbd, 0xfe, 0x04, 0x8b, 0xaf, 0xd5, 0xa0, 0x3a, 0x9e, 0x5c,
	0x5f, 0xdb, 0xe3, 0xb1, 0xa9, 0x9c, 0xff, 0x53, 0x02, 0xf5, 0xd6, 0x0b, 0xd0, 0x05, 0x54, 0x24,
	0x86, 0xa0, 0x0f, 0x85, 0x91, 0xcd, 0x84, 0x6f, 0x7e, 0xdc, 0xca, 0x66, 0x06, 0x38, 0x03, 0x4d,
	0x3c, 0x27, 0xc8, 0x5c, 0xbf, 0x2c, 0x2b, 0xc0, 0xa7, 0xfc, 0xe4, 0xe5, 0x07, 0xf7, 0x02, 0xaa,
	0xd9, 0xd8, 0xa1, 0xf7, 0x6b, 0x03, 0x6c, 0x86, 0x50, 0x30, 0x65, 0x7f, 0x9b, 0x2b, 0xc6, 0x82,
	0x35, 0xec, 0x07, 0x00, 0xe9, 0x06, 0x12, 0xb2, 0x27, 0x82, 0xde, 0x4a, 0xe4, 0x66, 0x70, 0x5e,
	0x42, 0x65, 0x8e, 0xc7, 0x84, 0xc7, 0x94, 0x3c, 0x11, 0xe1, 0xb3, 0x9d, 0xd8, 0x1d, 0x3e, 0x44,
	0x97, 0x60, 0xac, 0xfd, 0x87, 0x36, 0x67, 0xf2, 0x7e, 0x6c, 0x7e, 0x53, 0x80, 0xae, 0x9b, 0xbc,
	0xfa, 0xee, 0x97, 0x6f, 0x67, 0x94, 0xff, 0xba, 0x78, 0x38, 0x79, 0x64, 0xe1, 0xa9, 0xcf, 0x62,
	0x4e, 0x7d, 0x7a, 0x2a, 0x7f, 0x9f, 0xc7, 0x33, 0x76, 0xea, 0x7b, 0xc1, 0x43, 0x45, 0xae, 0xbe,
	0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xe7, 0xcd, 0xee, 0x6d, 0x07, 0x00, 0x00,
}
