// Code generated by protoc-gen-go.
// source: platform.proto
// DO NOT EDIT!

/*
Package platform is a generated protocol buffer package.

It is generated from these files:
	platform.proto

It has these top-level messages:
	HttpRequest
	HttpResponse
	SocketRequest
*/
package platform

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocketAction int32

const (
	SocketAction_SUBSCRIBE   SocketAction = 0
	SocketAction_UNSUBSCRIBE SocketAction = 1
)

var SocketAction_name = map[int32]string{
	0: "SUBSCRIBE",
	1: "UNSUBSCRIBE",
}
var SocketAction_value = map[string]int32{
	"SUBSCRIBE":   0,
	"UNSUBSCRIBE": 1,
}

func (x SocketAction) String() string {
	return proto.EnumName(SocketAction_name, int32(x))
}
func (SocketAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HttpRequest struct {
	Path        string                                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Method      string                                `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	PostParams  map[string]*HttpRequest_HttpParameter `protobuf:"bytes,3,rep,name=post_params,json=postParams" json:"post_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryParams map[string]*HttpRequest_HttpParameter `protobuf:"bytes,4,rep,name=query_params,json=queryParams" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body        string                                `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	Language    string                                `protobuf:"bytes,6,opt,name=language" json:"language,omitempty"`
	ContentType string                                `protobuf:"bytes,7,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
}

func (m *HttpRequest) Reset()                    { *m = HttpRequest{} }
func (m *HttpRequest) String() string            { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()               {}
func (*HttpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HttpRequest) GetPostParams() map[string]*HttpRequest_HttpParameter {
	if m != nil {
		return m.PostParams
	}
	return nil
}

func (m *HttpRequest) GetQueryParams() map[string]*HttpRequest_HttpParameter {
	if m != nil {
		return m.QueryParams
	}
	return nil
}

type HttpRequest_HttpParameter struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *HttpRequest_HttpParameter) Reset()                    { *m = HttpRequest_HttpParameter{} }
func (m *HttpRequest_HttpParameter) String() string            { return proto.CompactTextString(m) }
func (*HttpRequest_HttpParameter) ProtoMessage()               {}
func (*HttpRequest_HttpParameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type HttpResponse struct {
	StatusCode  int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Body        string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Language    string `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
}

func (m *HttpResponse) Reset()                    { *m = HttpResponse{} }
func (m *HttpResponse) String() string            { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()               {}
func (*HttpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SocketRequest struct {
	SocketId string       `protobuf:"bytes,1,opt,name=socket_id,json=socketId" json:"socket_id,omitempty"`
	Action   SocketAction `protobuf:"varint,2,opt,name=action,enum=platform.SocketAction" json:"action,omitempty"`
	Payload  string       `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *SocketRequest) Reset()                    { *m = SocketRequest{} }
func (m *SocketRequest) String() string            { return proto.CompactTextString(m) }
func (*SocketRequest) ProtoMessage()               {}
func (*SocketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*HttpRequest)(nil), "platform.HttpRequest")
	proto.RegisterType((*HttpRequest_HttpParameter)(nil), "platform.HttpRequest.HttpParameter")
	proto.RegisterType((*HttpResponse)(nil), "platform.HttpResponse")
	proto.RegisterType((*SocketRequest)(nil), "platform.SocketRequest")
	proto.RegisterEnum("platform.SocketAction", SocketAction_name, SocketAction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for FortifiPlatform service

type FortifiPlatformClient interface {
	HandleHttpRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	HandleSocketAction(ctx context.Context, in *SocketRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type fortifiPlatformClient struct {
	cc *grpc.ClientConn
}

func NewFortifiPlatformClient(cc *grpc.ClientConn) FortifiPlatformClient {
	return &fortifiPlatformClient{cc}
}

func (c *fortifiPlatformClient) HandleHttpRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	out := new(HttpResponse)
	err := grpc.Invoke(ctx, "/platform.FortifiPlatform/HandleHttpRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fortifiPlatformClient) HandleSocketAction(ctx context.Context, in *SocketRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	out := new(HttpResponse)
	err := grpc.Invoke(ctx, "/platform.FortifiPlatform/HandleSocketAction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FortifiPlatform service

type FortifiPlatformServer interface {
	HandleHttpRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	HandleSocketAction(context.Context, *SocketRequest) (*HttpResponse, error)
}

func RegisterFortifiPlatformServer(s *grpc.Server, srv FortifiPlatformServer) {
	s.RegisterService(&_FortifiPlatform_serviceDesc, srv)
}

func _FortifiPlatform_HandleHttpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FortifiPlatformServer).HandleHttpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.FortifiPlatform/HandleHttpRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FortifiPlatformServer).HandleHttpRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FortifiPlatform_HandleSocketAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FortifiPlatformServer).HandleSocketAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.FortifiPlatform/HandleSocketAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FortifiPlatformServer).HandleSocketAction(ctx, req.(*SocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FortifiPlatform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "platform.FortifiPlatform",
	HandlerType: (*FortifiPlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHttpRequest",
			Handler:    _FortifiPlatform_HandleHttpRequest_Handler,
		},
		{
			MethodName: "HandleSocketAction",
			Handler:    _FortifiPlatform_HandleSocketAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("platform.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xad, 0x31, 0x10, 0x18, 0x43, 0xa0, 0x23, 0x95, 0x5a, 0xee, 0xa1, 0x29, 0x55, 0xdb, 0xa8,
	0x07, 0x1f, 0xe8, 0xa5, 0xed, 0xad, 0x44, 0x44, 0xe1, 0x52, 0x51, 0xd3, 0x9c, 0xd1, 0x62, 0x6f,
	0x12, 0x14, 0xe3, 0xdd, 0xd8, 0x43, 0x24, 0x5f, 0xfb, 0x07, 0xbd, 0xf7, 0x63, 0x6b, 0xaf, 0x17,
	0x30, 0x2e, 0x52, 0x2f, 0xb9, 0xed, 0x3c, 0xbf, 0x7d, 0x6f, 0xe6, 0x8d, 0x17, 0x4e, 0x65, 0xc8,
	0xe8, 0x46, 0xc4, 0x6b, 0x57, 0xc6, 0x82, 0x04, 0xb6, 0xb6, 0xf5, 0xf0, 0x77, 0x1d, 0xac, 0x2b,
	0x22, 0xe9, 0xf1, 0x87, 0x0d, 0x4f, 0x08, 0x11, 0xea, 0x92, 0xd1, 0x9d, 0x6d, 0x9c, 0x19, 0xe7,
	0x6d, 0x4f, 0x9d, 0x71, 0x00, 0xcd, 0x35, 0xa7, 0x3b, 0x11, 0xd8, 0x35, 0x85, 0xea, 0x0a, 0x2f,
	0xc1, 0x92, 0x22, 0xa1, 0x85, 0x64, 0x31, 0x5b, 0x27, 0xb6, 0x79, 0x66, 0x9e, 0x5b, 0xa3, 0x77,
	0xee, 0xce, 0xab, 0xa4, 0xeb, 0xce, 0x32, 0xe2, 0x4c, 0xf1, 0x26, 0x11, 0xc5, 0xa9, 0x07, 0x72,
	0x07, 0xe0, 0x14, 0x3a, 0x19, 0x29, 0x4e, 0xb7, 0x42, 0x75, 0x25, 0xf4, 0xfe, 0xb8, 0xd0, 0x8f,
	0x9c, 0x59, 0x56, 0xb2, 0x1e, 0xf6, 0x48, 0xde, 0xfe, 0x52, 0x04, 0xa9, 0xdd, 0x28, 0xda, 0xcf,
	0xcf, 0xe8, 0x40, 0x2b, 0x64, 0xd1, 0xed, 0x86, 0xdd, 0x72, 0xbb, 0xa9, 0xf0, 0x5d, 0x8d, 0x6f,
	0xa0, 0xe3, 0x8b, 0x88, 0x78, 0x44, 0x0b, 0x4a, 0x25, 0xb7, 0x4f, 0xd4, 0x77, 0x4b, 0x63, 0x3f,
	0x33, 0xc8, 0xf9, 0x00, 0xdd, 0xdc, 0x5f, 0x19, 0x70, 0xe2, 0x71, 0x1e, 0xc7, 0x23, 0x0b, 0xb3,
	0x66, 0xb2, 0x90, 0xcc, 0x3c, 0x8e, 0xa2, 0x72, 0x96, 0xd0, 0xab, 0x4c, 0x89, 0x7d, 0x30, 0xef,
	0x79, 0xaa, 0xc3, 0xcc, 0x8f, 0xf8, 0x05, 0x1a, 0x8a, 0xae, 0xa2, 0xb4, 0x46, 0x6f, 0x8f, 0x0f,
	0x79, 0x60, 0xe8, 0x15, 0x37, 0xbe, 0xd6, 0x3e, 0x1b, 0x8e, 0x0f, 0xfd, 0x6a, 0x00, 0x4f, 0x6e,
	0x32, 0xfc, 0x65, 0x40, 0xa7, 0x20, 0x26, 0x52, 0x44, 0x09, 0xc7, 0xd7, 0x60, 0x25, 0xc4, 0x68,
	0x93, 0x2c, 0x7c, 0x11, 0x70, 0xe5, 0xd4, 0xf0, 0xa0, 0x80, 0x2e, 0x32, 0x64, 0x17, 0x7b, 0xad,
	0x14, 0x7b, 0x35, 0x5a, 0xf3, 0x9f, 0x68, 0x0f, 0x36, 0x53, 0x3f, 0xdc, 0xcc, 0xf0, 0x11, 0xba,
	0x73, 0xe1, 0xdf, 0x73, 0xda, 0xfe, 0x99, 0xaf, 0xa0, 0x9d, 0x28, 0x60, 0xb1, 0x0a, 0xf4, 0xb0,
	0xad, 0x02, 0x98, 0x06, 0xe8, 0x42, 0x93, 0xf9, 0xb4, 0x12, 0x91, 0x6a, 0xe1, 0x74, 0x34, 0xd8,
	0x8f, 0x5c, 0xa8, 0x7c, 0x53, 0x5f, 0x3d, 0xcd, 0x42, 0x1b, 0x4e, 0x24, 0x4b, 0x43, 0xc1, 0x02,
	0xdd, 0xd7, 0xb6, 0xfc, 0xe8, 0x42, 0xa7, 0x7c, 0x03, 0xbb, 0xd0, 0x9e, 0x5f, 0x8f, 0xe7, 0x17,
	0xde, 0x74, 0x3c, 0xe9, 0x3f, 0xc3, 0x1e, 0x58, 0xd7, 0xdf, 0xf7, 0x80, 0x31, 0xfa, 0x63, 0x40,
	0xef, 0x52, 0xc4, 0xb4, 0xba, 0x59, 0xcd, 0xb4, 0x25, 0x8e, 0xe1, 0xf9, 0x15, 0x8b, 0x82, 0x90,
	0x97, 0x5f, 0xd6, 0x8b, 0xa3, 0x5b, 0x70, 0x06, 0x55, 0x58, 0x67, 0x3e, 0x01, 0x2c, 0x34, 0x0e,
	0xba, 0x79, 0x59, 0x9d, 0xeb, 0x3f, 0x32, 0xcb, 0xa6, 0x7a, 0xf0, 0x9f, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x24, 0x58, 0xda, 0x02, 0x04, 0x00, 0x00,
}
