// Code generated by protoc-gen-go.
// source: ftypes/product.proto
// DO NOT EDIT!

/*
Package product is a generated protocol buffer package.

It is generated from these files:
	ftypes/product.proto

It has these top-level messages:
	Product
	ProductGroup
	ProductFeature
*/
package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductType int32

const (
	ProductType_PRODUCT ProductType = 0
	ProductType_SERVICE ProductType = 1
)

var ProductType_name = map[int32]string{
	0: "PRODUCT",
	1: "SERVICE",
}
var ProductType_value = map[string]int32{
	"PRODUCT": 0,
	"SERVICE": 1,
}

func (x ProductType) String() string {
	return proto.EnumName(ProductType_name, int32(x))
}
func (ProductType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Product struct {
	Id              string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code            string      `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Name            string      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Group           string      `protobuf:"bytes,4,opt,name=group" json:"group,omitempty"`
	Type            ProductType `protobuf:"varint,5,opt,name=type,enum=fortifi.product.ProductType" json:"type,omitempty"`
	Description     string      `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	ParentProductId string      `protobuf:"bytes,7,opt,name=parent_product_id,json=parentProductId" json:"parent_product_id,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Product) GetType() ProductType {
	if m != nil {
		return m.Type
	}
	return ProductType_PRODUCT
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetParentProductId() string {
	if m != nil {
		return m.ParentProductId
	}
	return ""
}

type ProductGroup struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *ProductGroup) Reset()                    { *m = ProductGroup{} }
func (m *ProductGroup) String() string            { return proto.CompactTextString(m) }
func (*ProductGroup) ProtoMessage()               {}
func (*ProductGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProductGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductGroup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ProductFeature struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	ProductId   string `protobuf:"bytes,3,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
}

func (m *ProductFeature) Reset()                    { *m = ProductFeature{} }
func (m *ProductFeature) String() string            { return proto.CompactTextString(m) }
func (*ProductFeature) ProtoMessage()               {}
func (*ProductFeature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProductFeature) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductFeature) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ProductFeature) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductFeature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductFeature) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "fortifi.product.Product")
	proto.RegisterType((*ProductGroup)(nil), "fortifi.product.ProductGroup")
	proto.RegisterType((*ProductFeature)(nil), "fortifi.product.ProductFeature")
	proto.RegisterEnum("fortifi.product.ProductType", ProductType_name, ProductType_value)
}

func init() { proto.RegisterFile("ftypes/product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xdd, 0x52, 0x20, 0x0c, 0x06, 0x70, 0xc3, 0x61, 0x0f, 0x9a, 0x90, 0x5e, 0x24, 0x8d,
	0xb6, 0x46, 0xdf, 0x40, 0x44, 0xc3, 0x49, 0x52, 0xab, 0x07, 0x2f, 0xa4, 0x74, 0xb7, 0x75, 0x0f,
	0x74, 0x37, 0xcb, 0xf6, 0xc0, 0x23, 0xf8, 0x84, 0xbe, 0x8e, 0xe9, 0x76, 0x35, 0x15, 0x34, 0xf1,
	0x36, 0xf3, 0xef, 0xe4, 0x9f, 0x6f, 0x66, 0x07, 0xc6, 0x99, 0xde, 0x49, 0xb6, 0x0d, 0xa5, 0x12,
	0xb4, 0x4c, 0x75, 0x20, 0x95, 0xd0, 0x02, 0x0f, 0x33, 0xa1, 0x34, 0xcf, 0x78, 0x60, 0x65, 0xef,
	0x03, 0x41, 0x77, 0x59, 0xc7, 0x78, 0x00, 0x0e, 0xa7, 0x04, 0x4d, 0xd0, 0xb4, 0x17, 0x39, 0x9c,
	0x62, 0x0c, 0x6e, 0x2a, 0x28, 0x23, 0x8e, 0x51, 0x4c, 0x5c, 0x69, 0x45, 0xb2, 0x61, 0xa4, 0x55,
	0x6b, 0x55, 0x8c, 0xc7, 0xd0, 0xce, 0x95, 0x28, 0x25, 0x71, 0x8d, 0x58, 0x27, 0xf8, 0x0a, 0xdc,
	0x8a, 0x80, 0xb4, 0x27, 0x68, 0x3a, 0xb8, 0x3e, 0x0d, 0xf6, 0x3a, 0x07, 0xb6, 0x6b, 0xbc, 0x93,
	0x2c, 0x32, 0x95, 0x78, 0x02, 0x7d, 0xca, 0xb6, 0xa9, 0xe2, 0x52, 0x73, 0x51, 0x90, 0x8e, 0x71,
	0x6b, 0x4a, 0xd8, 0x87, 0x13, 0x99, 0x28, 0x56, 0xe8, 0x95, 0x75, 0x59, 0x71, 0x4a, 0xba, 0xa6,
	0x6e, 0x58, 0x3f, 0x58, 0xd7, 0x05, 0xf5, 0x62, 0x38, 0xb6, 0xc9, 0x83, 0xe1, 0xf9, 0x65, 0x3a,
	0x33, 0x89, 0xd3, 0x98, 0x64, 0x8f, 0xa0, 0x75, 0x40, 0xe0, 0xbd, 0x23, 0x18, 0x58, 0xdb, 0x7b,
	0x96, 0xe8, 0x52, 0xb1, 0x7f, 0xad, 0xed, 0x0c, 0xa0, 0x41, 0x5c, 0xfb, 0xf6, 0xe4, 0x17, 0xeb,
	0x37, 0x8b, 0xfb, 0x37, 0x4b, 0xfb, 0x80, 0xc5, 0x3f, 0x87, 0x7e, 0x63, 0x89, 0xb8, 0x0f, 0xdd,
	0x65, 0xf4, 0x78, 0xf7, 0x3c, 0x8b, 0x47, 0x47, 0x55, 0xf2, 0x34, 0x8f, 0x5e, 0x16, 0xb3, 0xf9,
	0x08, 0xdd, 0x5e, 0xbc, 0xfa, 0x39, 0xd7, 0x6f, 0xe5, 0x3a, 0x48, 0xc5, 0x26, 0xb4, 0x1f, 0x11,
	0x9a, 0x8b, 0xb8, 0xcc, 0x45, 0xf8, 0xf3, 0x52, 0xd6, 0x1d, 0xf3, 0x70, 0xf3, 0x19, 0x00, 0x00,
	0xff, 0xff, 0x3b, 0xb2, 0x54, 0xa2, 0x42, 0x02, 0x00, 0x00,
}
